import { HttpStatus } from '@nestjs/common';

/**
 * Makine-okunur hata kodları. İstemci davranışı `code` üzerinden belirlenir;
 * `message` yalnızca kullanıcıya gösterim içindir ve değişebilir.
 */
export const ERROR_CODES = {
  // Genel
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // Kimlik ve yetki
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  PHONE_NOT_VERIFIED: 'PHONE_NOT_VERIFIED',
  FORBIDDEN: 'FORBIDDEN',
  FORBIDDEN_RESOURCE: 'FORBIDDEN_RESOURCE',

  // Usta
  MASTER_NOT_VERIFIED: 'MASTER_NOT_VERIFIED',
  MASTER_PROFILE_INCOMPLETE: 'MASTER_PROFILE_INCOMPLETE',

  // İş talebi
  JOB_NOT_OPEN_FOR_OFFERS: 'JOB_NOT_OPEN_FOR_OFFERS',
  JOB_INVALID_STATUS_TRANSITION: 'JOB_INVALID_STATUS_TRANSITION',

  // Teklif
  DUPLICATE_OFFER: 'DUPLICATE_OFFER',
  OFFER_ALREADY_ACCEPTED: 'OFFER_ALREADY_ACCEPTED',
  OFFER_EXPIRED: 'OFFER_EXPIRED',
  OFFER_NOT_PENDING: 'OFFER_NOT_PENDING',

  // Ödeme
  PAYMENT_REQUIRED: 'PAYMENT_REQUIRED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_ALREADY_PROCESSED: 'PAYMENT_ALREADY_PROCESSED',

  // Dosya
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
  UPLOAD_LIMIT_EXCEEDED: 'UPLOAD_LIMIT_EXCEEDED',

  // Değerlendirme
  REVIEW_NOT_ALLOWED: 'REVIEW_NOT_ALLOWED',
  REVIEW_ALREADY_EXISTS: 'REVIEW_ALREADY_EXISTS',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/** Hata kodlarının varsayılan HTTP durumu. */
export const ERROR_CODE_STATUS: Record<ErrorCode, HttpStatus> = {
  INTERNAL_ERROR: HttpStatus.INTERNAL_SERVER_ERROR,
  VALIDATION_ERROR: HttpStatus.UNPROCESSABLE_ENTITY,
  NOT_FOUND: HttpStatus.NOT_FOUND,
  CONFLICT: HttpStatus.CONFLICT,
  RATE_LIMITED: HttpStatus.TOO_MANY_REQUESTS,
  SERVICE_UNAVAILABLE: HttpStatus.SERVICE_UNAVAILABLE,

  UNAUTHORIZED: HttpStatus.UNAUTHORIZED,
  INVALID_CREDENTIALS: HttpStatus.UNAUTHORIZED,
  TOKEN_EXPIRED: HttpStatus.UNAUTHORIZED,
  TOKEN_INVALID: HttpStatus.UNAUTHORIZED,
  REFRESH_TOKEN_REUSED: HttpStatus.UNAUTHORIZED,
  ACCOUNT_LOCKED: HttpStatus.FORBIDDEN,
  ACCOUNT_SUSPENDED: HttpStatus.FORBIDDEN,
  EMAIL_NOT_VERIFIED: HttpStatus.FORBIDDEN,
  PHONE_NOT_VERIFIED: HttpStatus.FORBIDDEN,
  FORBIDDEN: HttpStatus.FORBIDDEN,
  FORBIDDEN_RESOURCE: HttpStatus.FORBIDDEN,

  MASTER_NOT_VERIFIED: HttpStatus.FORBIDDEN,
  MASTER_PROFILE_INCOMPLETE: HttpStatus.FORBIDDEN,

  JOB_NOT_OPEN_FOR_OFFERS: HttpStatus.CONFLICT,
  JOB_INVALID_STATUS_TRANSITION: HttpStatus.CONFLICT,

  DUPLICATE_OFFER: HttpStatus.CONFLICT,
  OFFER_ALREADY_ACCEPTED: HttpStatus.CONFLICT,
  OFFER_EXPIRED: HttpStatus.CONFLICT,
  OFFER_NOT_PENDING: HttpStatus.CONFLICT,

  PAYMENT_REQUIRED: HttpStatus.PAYMENT_REQUIRED,
  PAYMENT_FAILED: HttpStatus.BAD_REQUEST,
  PAYMENT_ALREADY_PROCESSED: HttpStatus.CONFLICT,

  FILE_TOO_LARGE: HttpStatus.PAYLOAD_TOO_LARGE,
  UNSUPPORTED_FILE_TYPE: HttpStatus.UNSUPPORTED_MEDIA_TYPE,
  UPLOAD_LIMIT_EXCEEDED: HttpStatus.BAD_REQUEST,

  REVIEW_NOT_ALLOWED: HttpStatus.FORBIDDEN,
  REVIEW_ALREADY_EXISTS: HttpStatus.CONFLICT,
};
