/**
 * Makine-okunur hata kodları. İstemci davranışı `code` üzerinden belirlenir;
 * `message` yalnızca kullanıcıya gösterim içindir ve değişebilir.
 *
 * Bu liste tek kaynaktır: backend hatayı üretir, web/admin/mobil aynı koda göre
 * davranır. Framework'e bağımlı olmaması için HTTP durumları düz sayı tutulur.
 */
export const ERROR_CODES = {
  // Genel
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // Kimlik ve yetki
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  PHONE_ALREADY_EXISTS: 'PHONE_ALREADY_EXISTS',
  USERNAME_TAKEN: 'USERNAME_TAKEN',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  PHONE_NOT_VERIFIED: 'PHONE_NOT_VERIFIED',
  FORBIDDEN: 'FORBIDDEN',
  FORBIDDEN_RESOURCE: 'FORBIDDEN_RESOURCE',

  // Satıcı
  PROVIDER_NOT_VERIFIED: 'PROVIDER_NOT_VERIFIED',
  PROVIDER_PROFILE_INCOMPLETE: 'PROVIDER_PROFILE_INCOMPLETE',
  PROVIDER_OUT_OF_SERVICE_AREA: 'PROVIDER_OUT_OF_SERVICE_AREA',

  // İş talebi
  JOB_NOT_OPEN_FOR_OFFERS: 'JOB_NOT_OPEN_FOR_OFFERS',
  JOB_INVALID_STATUS_TRANSITION: 'JOB_INVALID_STATUS_TRANSITION',

  // Teklif
  DUPLICATE_OFFER: 'DUPLICATE_OFFER',
  OFFER_ALREADY_ACCEPTED: 'OFFER_ALREADY_ACCEPTED',
  OFFER_EXPIRED: 'OFFER_EXPIRED',
  OFFER_NOT_PENDING: 'OFFER_NOT_PENDING',
  OFFER_INVALID_STATUS_TRANSITION: 'OFFER_INVALID_STATUS_TRANSITION',

  // Sipariş
  ORDER_INVALID_STATUS_TRANSITION: 'ORDER_INVALID_STATUS_TRANSITION',

  // Ödeme
  PAYMENT_REQUIRED: 'PAYMENT_REQUIRED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_ALREADY_PROCESSED: 'PAYMENT_ALREADY_PROCESSED',
  PAYMENT_NOT_REFUNDABLE: 'PAYMENT_NOT_REFUNDABLE',
  PAYMENT_WEBHOOK_INVALID: 'PAYMENT_WEBHOOK_INVALID',

  // Dosya
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
  UPLOAD_LIMIT_EXCEEDED: 'UPLOAD_LIMIT_EXCEEDED',

  // Değerlendirme
  REVIEW_NOT_ALLOWED: 'REVIEW_NOT_ALLOWED',
  REVIEW_ALREADY_EXISTS: 'REVIEW_ALREADY_EXISTS',

  // AI faturalama
  AI_CREDITS_EXHAUSTED: 'AI_CREDITS_EXHAUSTED',
  AI_FEATURE_NOT_IN_PLAN: 'AI_FEATURE_NOT_IN_PLAN',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/** Hata kodlarının varsayılan HTTP durumu. */
export const ERROR_CODE_STATUS: Record<ErrorCode, number> = {
  INTERNAL_ERROR: 500,
  VALIDATION_ERROR: 422,
  NOT_FOUND: 404,
  CONFLICT: 409,
  RATE_LIMITED: 429,
  SERVICE_UNAVAILABLE: 503,

  UNAUTHORIZED: 401,
  INVALID_CREDENTIALS: 401,
  TOKEN_EXPIRED: 401,
  TOKEN_INVALID: 401,
  REFRESH_TOKEN_INVALID: 401,
  REFRESH_TOKEN_REUSED: 401,
  EMAIL_ALREADY_EXISTS: 409,
  PHONE_ALREADY_EXISTS: 409,
  USERNAME_TAKEN: 409,
  ACCOUNT_LOCKED: 403,
  ACCOUNT_SUSPENDED: 403,
  EMAIL_NOT_VERIFIED: 403,
  PHONE_NOT_VERIFIED: 403,
  FORBIDDEN: 403,
  FORBIDDEN_RESOURCE: 403,

  PROVIDER_NOT_VERIFIED: 403,
  PROVIDER_PROFILE_INCOMPLETE: 403,
  PROVIDER_OUT_OF_SERVICE_AREA: 403,

  JOB_NOT_OPEN_FOR_OFFERS: 409,
  JOB_INVALID_STATUS_TRANSITION: 409,

  DUPLICATE_OFFER: 409,
  OFFER_ALREADY_ACCEPTED: 409,
  OFFER_EXPIRED: 409,
  OFFER_NOT_PENDING: 409,
  OFFER_INVALID_STATUS_TRANSITION: 409,

  ORDER_INVALID_STATUS_TRANSITION: 409,

  PAYMENT_REQUIRED: 402,
  PAYMENT_FAILED: 400,
  PAYMENT_ALREADY_PROCESSED: 409,
  PAYMENT_NOT_REFUNDABLE: 409,
  // Doğrulanamayan webhook isteği kimliksiz sayılır; gövdesine bakılmaz.
  PAYMENT_WEBHOOK_INVALID: 401,

  FILE_TOO_LARGE: 413,
  UNSUPPORTED_FILE_TYPE: 415,
  UPLOAD_LIMIT_EXCEEDED: 400,

  REVIEW_NOT_ALLOWED: 403,
  REVIEW_ALREADY_EXISTS: 409,

  AI_CREDITS_EXHAUSTED: 402,
  AI_FEATURE_NOT_IN_PLAN: 403,
};
