import type { SupportedLocale } from '@talpio/config';

export interface UnitOption {
  id: string;
  labels: Partial<Record<SupportedLocale, string>> & { tr: string; en: string };
}

const UNITS: UnitOption[] = [
  { id: 'adet', labels: { tr: 'Adet', en: 'Piece', de: 'Stück', es: 'Unidad', fr: 'Pièce', ar: 'قطعة' } },
  { id: 'kg', labels: { tr: 'Kg', en: 'Kg', de: 'Kg', es: 'Kg', fr: 'Kg', ar: 'كغ' } },
  { id: 'g', labels: { tr: 'Gram', en: 'Gram', de: 'Gramm', es: 'Gramo', fr: 'Gramme', ar: 'غرام' } },
  { id: 'ton', labels: { tr: 'Ton', en: 'Ton', de: 'Tonne', es: 'Tonelada', fr: 'Tonne', ar: 'طن' } },
  { id: 'litre', labels: { tr: 'Litre', en: 'Litre', de: 'Liter', es: 'Litro', fr: 'Litre', ar: 'لتر' } },
  { id: 'ml', labels: { tr: 'Mililitre', en: 'Millilitre', de: 'Milliliter', es: 'Mililitro', fr: 'Millilitre', ar: 'مل' } },
  { id: 'm3', labels: { tr: 'Metreküp', en: 'Cubic meter', de: 'Kubikmeter', es: 'Metro cúbico', fr: 'Mètre cube', ar: 'متر مكعب' } },
  { id: 'metre', labels: { tr: 'Metre', en: 'Meter', de: 'Meter', es: 'Metro', fr: 'Mètre', ar: 'متر' } },
  { id: 'cm', labels: { tr: 'Santimetre', en: 'Centimeter', de: 'Zentimeter', es: 'Centímetro', fr: 'Centimètre', ar: 'سم' } },
  { id: 'mm', labels: { tr: 'Milimetre', en: 'Millimeter', de: 'Millimeter', es: 'Milímetro', fr: 'Millimètre', ar: 'مم' } },
  { id: 'm2', labels: { tr: 'Metrekare', en: 'Square meter', de: 'Quadratmeter', es: 'Metro cuadrado', fr: 'Mètre carré', ar: 'متر مربع' } },
  { id: 'paket', labels: { tr: 'Paket', en: 'Pack', de: 'Packung', es: 'Paquete', fr: 'Paquet', ar: 'عبوة' } },
  { id: 'koli', labels: { tr: 'Koli', en: 'Carton', de: 'Karton', es: 'Caja', fr: 'Carton', ar: 'كرتون' } },
  { id: 'kutu', labels: { tr: 'Kutu', en: 'Box', de: 'Kiste', es: 'Caja', fr: 'Boîte', ar: 'صندوق' } },
  { id: 'palet', labels: { tr: 'Palet', en: 'Pallet', de: 'Palette', es: 'Palé', fr: 'Palette', ar: 'منصة' } },
  { id: 'rulo', labels: { tr: 'Rulo', en: 'Roll', de: 'Rolle', es: 'Rollo', fr: 'Rouleau', ar: 'لفة' } },
  { id: 'top', labels: { tr: 'Top (kumaş)', en: 'Bolt (fabric)', de: 'Stoffballen', es: 'Pieza de tela', fr: 'Pièce de tissu', ar: 'طابة قماش' } },
  { id: 'set', labels: { tr: 'Set', en: 'Set', de: 'Set', es: 'Set', fr: 'Set', ar: 'طقم' } },
  { id: 'takim', labels: { tr: 'Takım', en: 'Kit', de: 'Satz', es: 'Juego', fr: 'Kit', ar: 'طقم' } },
  { id: 'cift', labels: { tr: 'Çift', en: 'Pair', de: 'Paar', es: 'Par', fr: 'Paire', ar: 'زوج' } },
  { id: 'duzine', labels: { tr: 'Düzine', en: 'Dozen', de: 'Dutzend', es: 'Docena', fr: 'Douzaine', ar: 'دزينة' } },
  { id: 'cuval', labels: { tr: 'Çuval', en: 'Sack', de: 'Sack', es: 'Saco', fr: 'Sac', ar: 'كيس' } },
  { id: 'bidon', labels: { tr: 'Bidon', en: 'Jerrycan', de: 'Kanister', es: 'Bidón', fr: 'Bidon', ar: 'صفائح' } },
  { id: 'varil', labels: { tr: 'Varil', en: 'Barrel', de: 'Fass', es: 'Barril', fr: 'Fût', ar: 'برميل' } },
  { id: 'sise', labels: { tr: 'Şişe', en: 'Bottle', de: 'Flasche', es: 'Botella', fr: 'Bouteille', ar: 'زجاجة' } },
  { id: 'kasa', labels: { tr: 'Kasa', en: 'Crate', de: 'Steige', es: 'Cajón', fr: 'Caisse', ar: 'قفص' } },
  { id: 'torba', labels: { tr: 'Torba', en: 'Bag', de: 'Beutel', es: 'Bolsa', fr: 'Sac', ar: 'كيس' } },
  { id: 'paket-koli', labels: { tr: 'Paket / koli', en: 'Pack / carton', de: 'Packung / Karton', es: 'Paquete / caja', fr: 'Paquet / carton', ar: 'عبوة / كرتون' } },
  { id: 'saat', labels: { tr: 'Saat', en: 'Hour', de: 'Stunde', es: 'Hora', fr: 'Heure', ar: 'ساعة' } },
  { id: 'gun', labels: { tr: 'Gün', en: 'Day', de: 'Tag', es: 'Día', fr: 'Jour', ar: 'يوم' } },
  { id: 'ay', labels: { tr: 'Ay', en: 'Month', de: 'Monat', es: 'Mes', fr: 'Mois', ar: 'شهر' } },
  { id: 'kisi', labels: { tr: 'Kişi', en: 'Person', de: 'Person', es: 'Persona', fr: 'Personne', ar: 'شخص' } },
  { id: 'kw', labels: { tr: 'kW', en: 'kW', de: 'kW', es: 'kW', fr: 'kW', ar: 'ك.و' } },
  { id: 'ton-km', labels: { tr: 'Ton-km', en: 'Ton-km', de: 'Tonnenkilometer', es: 'Tonelada-km', fr: 'Tonne-km', ar: 'طن-كم' } },
];

export function commerceUnitOptions(locale: SupportedLocale): { id: string; label: string }[] {
  return UNITS.map((unit) => ({
    id: unit.id,
    label: unit.labels[locale] ?? unit.labels.en,
  }));
}

export const COMMERCE_BRANDS = [
  'Samsung',
  'LG',
  'Sony',
  'Philips',
  'Bosch',
  'Siemens',
  'Beko',
  'Arçelik',
  'Vestel',
  'Profilo',
  'Grundig',
  'Apple',
  'Xiaomi',
  'Huawei',
  'Oppo',
  'Lenovo',
  'HP',
  'Dell',
  'Asus',
  'Acer',
  'MSI',
  'Intel',
  'AMD',
  'NVIDIA',
  'Panasonic',
  'Sharp',
  'Toshiba',
  'Hitachi',
  'Daikin',
  'Mitsubishi',
  'Vaillant',
  'ECA',
  'Baymak',
  'Demirdöküm',
  'Warmhaus',
  'Caterpillar',
  'Komatsu',
  'JCB',
  'Volvo',
  'Mercedes-Benz',
  'BMW',
  'Ford',
  'Toyota',
  'Renault',
  'Fiat',
  'Tofaş',
  'Otokar',
  'BMC',
  'Ford Trucks',
  'Michelin',
  'Bridgestone',
  'Pirelli',
  'Goodyear',
  'Lassa',
  'Petlas',
  'Castrol',
  'Shell',
  'Mobil',
  'TotalEnergies',
  'BP',
  'Opel',
  '3M',
  'Bosch Rexroth',
  'Schneider Electric',
  'ABB',
  'Siemens Energy',
  'Legrand',
  'Makita',
  'DeWalt',
  'Bosch Professional',
  'Hilti',
  'Stanley',
  'IKEA',
  'Kelebek',
  'Bellona',
  'İstikbal',
  'Doğtaş',
  'Mondi',
  'Nestlé',
  'Ülker',
  'Eti',
  'Pınar',
  'Sütaş',
  'Banvit',
  'Erpiliç',
  'Torku',
  'Coca-Cola',
  'Pepsi',
  'Efes',
  'Unilever',
  'Procter & Gamble',
  'Henkel',
  'Hayat',
  'Evyap',
  'Komili',
  'Yudum',
  'Tork',
  'Selpak',
  'Solo',
  'Nike',
  'Adidas',
  'Puma',
  'Decathlon',
  'Zara',
  'LC Waikiki',
  'Koton',
  'Defacto',
  'Mavi',
  'Canon',
  'Nikon',
  'DJI',
  'GoPro',
  'Markasız / muadil',
  'Yerli üretim',
  'OEM',
  'Fark etmez',
];
