export const API_VERSION = 'v1';
export const API_PREFIX = `api/${API_VERSION}`;

/**
 * API yollarının tek kaynağı. Backend controller yolları, web/admin istemcileri
 * ve testler bu tanımları kullanır; yol değişikliği tek yerden yapılır.
 */
export const API_ROUTES = {
  auth: {
    register: '/auth/register',
    login: '/auth/login',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    logoutAll: '/auth/logout-all',
    me: '/auth/me',
    verifyEmail: '/auth/verify-email',
    requestEmailVerification: '/auth/verify-email/request',
    requestPhoneCode: '/auth/phone/request-code',
    verifyPhone: '/auth/phone/verify',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    changePassword: '/auth/change-password',
    sessions: '/auth/sessions',
  },
  users: {
    root: '/users',
    byId: (id: string) => `/users/${id}`,
    me: '/users/me',
    addresses: '/users/me/addresses',
    addressById: (id: string) => `/users/me/addresses/${id}`,
  },
  providers: {
    root: '/providers',
    byId: (id: string) => `/providers/${id}`,
    me: '/providers/me',
    services: '/providers/me/services',
    serviceAreas: '/providers/me/service-areas',
    availability: '/providers/me/availability',
    documents: '/providers/me/documents',
    earnings: '/providers/me/earnings',
    reviews: (id: string) => `/providers/${id}/reviews`,
    favorites: '/providers/favorites',
    favoriteById: (id: string) => `/providers/favorites/${id}`,
  },
  catalog: {
    categories: '/categories',
    categoryById: (id: string) => `/categories/${id}`,
    countries: '/locations/countries',
    cities: '/locations/cities',
    districts: '/locations/districts',
    neighborhoods: '/locations/neighborhoods',
  },
  jobs: {
    root: '/jobs',
    byId: (id: string) => `/jobs/${id}`,
    publish: (id: string) => `/jobs/${id}/publish`,
    cancel: (id: string) => `/jobs/${id}/cancel`,
    status: (id: string) => `/jobs/${id}/status`,
    attachments: (id: string) => `/jobs/${id}/attachments`,
    offers: (id: string) => `/jobs/${id}/offers`,
    /** Satıcıya açık iş havuzu. */
    available: '/jobs/available',
  },
  offers: {
    root: '/offers',
    byId: (id: string) => `/offers/${id}`,
    accept: (id: string) => `/offers/${id}/accept`,
    reject: (id: string) => `/offers/${id}/reject`,
    withdraw: (id: string) => `/offers/${id}/withdraw`,
    mine: '/offers/mine',
  },
  requests: {
    root: '/requests',
    mine: '/requests/mine',
    matched: '/requests/matched',
    byId: (id: string) => `/requests/${id}`,
    publish: (id: string) => `/requests/${id}/publish`,
    offers: (id: string) => `/requests/${id}/offers`,
  },
  requestOffers: {
    accept: (id: string) => `/request-offers/${id}/accept`,
  },
  businesses: {
    supplier: '/businesses/supplier',
    mine: '/businesses/mine',
    localeSettings: (id: string) => `/businesses/${id}/locale-settings`,
    crmCustomers: (id: string) => `/businesses/${id}/crm/customers`,
    crmCustomer: (id: string, customerId: string) =>
      `/businesses/${id}/crm/customers/${customerId}`,
    crmNotes: (id: string, customerId: string) =>
      `/businesses/${id}/crm/customers/${customerId}/notes`,
    crmFollowUps: (id: string, customerId: string) =>
      `/businesses/${id}/crm/customers/${customerId}/follow-ups`,
    crmFollowUpComplete: (id: string, customerId: string, followUpId: string) =>
      `/businesses/${id}/crm/customers/${customerId}/follow-ups/${followUpId}/complete`,
    crmAnalytics: (id: string) => `/businesses/${id}/crm/analytics`,
    workOrders: (id: string) => `/businesses/${id}/work-orders`,
    workOrderBoard: (id: string) => `/businesses/${id}/work-orders/board`,
    workOrderStage: (id: string, workOrderId: string) =>
      `/businesses/${id}/work-orders/${workOrderId}/stage`,
    workOrderAssign: (id: string, workOrderId: string) =>
      `/businesses/${id}/work-orders/${workOrderId}/assign`,
    tasks: (id: string) => `/businesses/${id}/tasks`,
    taskStatus: (id: string, taskId: string) => `/businesses/${id}/tasks/${taskId}/status`,
    dashboard: (id: string) => `/businesses/${id}/dashboard`,
    trustScore: (id: string) => `/businesses/${id}/trust-score`,
    campaigns: (id: string) => `/businesses/${id}/campaigns`,
  },
  orders: {
    root: '/orders',
    byId: (id: string) => `/orders/${id}`,
    /** Müşteri ödemeyi tamamlar; iş takvime alınır. */
    pay: (id: string) => `/orders/${id}/pay`,
    /** Satıcı işe başladığını bildirir. */
    start: (id: string) => `/orders/${id}/start`,
    /** Satıcı işi bitirir; müşteri onayı beklenir. */
    complete: (id: string) => `/orders/${id}/complete`,
    approve: (id: string) => `/orders/${id}/approve`,
    cancel: (id: string) => `/orders/${id}/cancel`,
  },
  messages: {
    /** Listeleme (GET) ve siparişin sohbetini açma (POST) aynı yolu kullanır. */
    conversations: '/messages/conversations',
    conversationById: (id: string) => `/messages/conversations/${id}`,
    messages: (conversationId: string) => `/messages/conversations/${conversationId}/messages`,
    read: (conversationId: string) => `/messages/conversations/${conversationId}/read`,
  },
  reviews: {
    root: '/reviews',
    byId: (id: string) => `/reviews/${id}`,
    reply: (id: string) => `/reviews/${id}/reply`,
  },
  realtime: {
    stream: '/realtime/stream',
  },
  social: {
    me: '/social/profiles/me',
    profileExperiences: '/social/profiles/me/experiences',
    profileExperience: (id: string) => `/social/profiles/me/experiences/${id}`,
    profileEducation: '/social/profiles/me/education',
    profileEducationItem: (id: string) => `/social/profiles/me/education/${id}`,
    profileSkills: '/social/profiles/me/skills',
    profileSkill: (id: string) => `/social/profiles/me/skills/${id}`,
    usernameAvailability: (username: string) =>
      `/social/profiles/availability/${encodeURIComponent(username)}`,
    profileSearch: '/social/profiles/search',
    profileByUsername: (username: string) => `/social/profiles/${username}`,
    follow: (username: string) => `/social/profiles/${username}/follow`,
    message: (username: string) => `/social/profiles/${username}/message`,
    followers: (username: string) => `/social/profiles/${username}/followers`,
    following: (username: string) => `/social/profiles/${username}/following`,
    postsByUsername: (username: string) => `/social/profiles/${username}/posts`,
    posts: '/social/posts',
    postById: (id: string) => `/social/posts/${id}`,
    createRequestFromPost: (id: string) => `/social/posts/${id}/create-request`,
    shareRequest: (requestId: string) => `/social/requests/${requestId}/share`,
    like: (id: string) => `/social/posts/${id}/like`,
    comments: (id: string) => `/social/posts/${id}/comments`,
    save: (id: string) => `/social/posts/${id}/save`,
    share: (id: string) => `/social/posts/${id}/share`,
    view: (id: string) => `/social/posts/${id}/view`,
    hide: (id: string) => `/social/posts/${id}/hide`,
    feed: '/social/feed',
    discover: '/social/discover',
    trending: '/social/trending',
    hashtagPosts: (slug: string) => `/social/hashtags/${encodeURIComponent(slug)}/posts`,
    categoryFollows: '/social/categories/following',
    categoryFollow: (categoryId: string) => `/social/categories/${categoryId}/follow`,
    interests: '/social/interests',
    analyticsMe: '/social/analytics/me',
    analyticsBusiness: (businessId: string) => `/social/analytics/business/${businessId}`,
    reports: '/social/reports',
    block: (userId: string) => `/social/blocks/${userId}`,
    /** Story / reel omurgası (iskelet) */
    saved: '/social/saved',
    stories: '/social/stories',
    highlights: '/social/highlights',
    highlightById: (id: string) => `/social/highlights/${id}`,
    highlightItems: (id: string) => `/social/highlights/${id}/items`,
    highlightItem: (highlightId: string, postId: string) =>
      `/social/highlights/${highlightId}/items/${postId}`,
    profileStories: (username: string) => `/social/profiles/${username}/stories`,
    profileHighlights: (username: string) => `/social/profiles/${username}/highlights`,
    profileHighlight: (username: string, highlightId: string) =>
      `/social/profiles/${username}/highlights/${highlightId}`,
    groupConversations: '/social/group-conversations',
    groupConversationMembers: (id: string) => `/social/group-conversations/${id}/members`,
  },
  notifications: {
    root: '/notifications',
    /** Rozetler tüm listeyi çekmesin diye ayrı ve hafif bir uç. */
    unreadCount: '/notifications/unread-count',
    read: (id: string) => `/notifications/${id}/read`,
    readAll: '/notifications/read-all',
    /** Kayıt (POST) ve silme (DELETE) aynı yolu kullanır; jeton gövdede taşınır. */
    deviceTokens: '/notifications/device-tokens',
    /** Yalnızca production dışında açık: mock sürücülerin gönderim tamponu. */
    mockOutbox: '/notifications/mock-outbox',
  },
  payments: {
    root: '/payments',
    byId: (id: string) => `/payments/${id}`,
    checkout: '/payments/checkout',
    webhook: '/payments/webhook',
    transactions: '/payments/transactions',
    /** Satıcının cüzdan özeti: kullanılabilir bakiye ve bloke hakediş. */
    wallet: '/payments/wallet',
    refund: (id: string) => `/payments/${id}/refund`,
  },
  support: {
    tickets: '/support/tickets',
    ticketById: (id: string) => `/support/tickets/${id}`,
    ticketMessages: (id: string) => `/support/tickets/${id}/messages`,
    ticketClose: (id: string) => `/support/tickets/${id}/close`,
    complaints: '/support/complaints',
  },
  files: {
    upload: '/files/upload',
    byId: (id: string) => `/files/${id}`,
  },
  agent: {
    threads: '/agent/threads',
    threadById: (id: string) => `/agent/threads/${id}`,
    messages: (id: string) => `/agent/threads/${id}/messages`,
    pendingActions: '/agent/actions/pending',
    approveAction: (id: string) => `/agent/actions/${id}/approve`,
    rejectAction: (id: string) => `/agent/actions/${id}/reject`,
    draftRequest: '/agent/drafts/request',
    draftOffer: '/agent/drafts/offer',
    draftSocial: '/agent/drafts/social',
    salesCoach: '/agent/sales-coach',
  },
  billing: {
    credits: '/billing/credits',
    transactions: '/billing/credits/transactions',
    usage: '/billing/usage',
    plans: '/billing/plans',
  },
  admin: {
    dashboard: '/admin/dashboard',
    users: '/admin/users',
    userById: (id: string) => `/admin/users/${id}`,
    userStatus: (id: string) => `/admin/users/${id}/status`,
    userRevokeSessions: (id: string) => `/admin/users/${id}/revoke-sessions`,
    providers: '/admin/providers',
    providerVerification: (id: string) => `/admin/providers/${id}/verification`,
    providerDocuments: '/admin/provider-documents',
    jobs: '/admin/jobs',
    offers: '/admin/offers',
    orders: '/admin/orders',
    payments: '/admin/payments',
    transactions: '/admin/transactions',
    commissions: '/admin/commissions',
    categories: '/admin/categories',
    categoryById: (id: string) => `/admin/categories/${id}`,
    locations: '/admin/locations',
    reviews: '/admin/reviews',
    reviewById: (id: string) => `/admin/reviews/${id}`,
    complaints: '/admin/complaints',
    complaintById: (id: string) => `/admin/complaints/${id}`,
    supportTickets: '/admin/support-tickets',
    supportTicketById: (id: string) => `/admin/support-tickets/${id}`,
    supportTicketMessages: (id: string) => `/admin/support-tickets/${id}/messages`,
    notifications: '/admin/notifications',
    settings: '/admin/settings',
    settingsRoles: '/admin/settings/roles',
    auditLogs: '/admin/audit-logs',
    subscriptions: '/admin/subscriptions',
    aiUsage: '/admin/ai-usage',
    campaigns: '/admin/campaigns',
    moderationReports: '/admin/moderation/reports',
    moderationReportById: (id: string) => `/admin/moderation/reports/${id}`,
    commerceRequests: '/admin/commerce-requests',
    fraudFlags: '/admin/fraud-flags',
    fraudFlagById: (id: string) => `/admin/fraud-flags/${id}`,
    backupStatus: '/admin/backup-status',
    backupVerify: '/admin/backup-status/verify',
    queueDeadLetters: '/admin/queues/dead-letters',
  },
  health: {
    live: '/health',
    ready: '/health/ready',
    metrics: '/health/metrics',
    status: '/health/status',
    queues: '/health/queues',
  },
} as const;
