import type { SupportedLocale } from '@talpio/config';

import {
  EXTRA_DEGREES_TR,
  EXTRA_DISTRICTS_TR,
  EXTRA_FIELDS_EN,
  EXTRA_FIELDS_TR,
  EXTRA_POSITIONS_EN,
  EXTRA_POSITIONS_TR,
  EXTRA_SCHOOLS,
  EXTRA_SHARED_SKILLS,
  EXTRA_SKILLS_EN,
  EXTRA_SKILLS_TR,
  EXTRA_WORLD_CITIES,
} from './career-examples-extra';

export type CareerExampleKind = 'skill' | 'position' | 'city' | 'school' | 'degree' | 'field';

const LIST_LIMIT = 40;

const SHARED_SKILLS = [
  'Microsoft Excel',
  'Microsoft Word',
  'Microsoft PowerPoint',
  'Microsoft Outlook',
  'Microsoft Teams',
  'Microsoft 365',
  'Microsoft Azure',
  'Microsoft Access',
  'Windows',
  'Linux',
  'macOS',
  'CRM',
  'ERP',
  'B2B',
  'B2C',
  'SAP',
  'Salesforce',
  'HubSpot',
  'AutoCAD',
  'SolidWorks',
  'Revit',
  'SketchUp',
  'SQL',
  'MySQL',
  'PostgreSQL',
  'Python',
  'Java',
  'JavaScript',
  'TypeScript',
  'HTML',
  'CSS',
  'React',
  'Node.js',
  'PHP',
  'C#',
  'C++',
  '.NET',
  'Git',
  'Docker',
  'Photoshop',
  'Illustrator',
  'InDesign',
  'Figma',
  'Canva',
  'After Effects',
  'Premiere Pro',
  'Power BI',
  'Tableau',
  'Google Analytics',
  'Google Ads',
  'Meta Ads',
  'SEO',
  'SEM',
  'Excel',
  'Word',
  'PowerPoint',
  'Outlook',
  'Teams',
  'Zoom',
  'Slack',
  'Jira',
  'Trello',
  'Notion',
  'WordPress',
  'Shopify',
  'AutoCAD Electrical',
  'PLC',
  'CNC',
  'ISO 9001',
  'Kaizen',
  'Lean',
  'Six Sigma',
  'Agile',
  'Scrum',
];

const LOCALE_SKILLS: Record<SupportedLocale, string[]> = {
  tr: [
    'Satış',
    'Satış yönetimi',
    'Saha satışı',
    'İç satış',
    'Pazarlama',
    'Dijital pazarlama',
    'İçerik pazarlama',
    'Marka yönetimi',
    'Müzakere',
    'Proje yönetimi',
    'Ürün yönetimi',
    'Muhasebe',
    'Finans',
    'Bütçe planlama',
    'Mali analiz',
    'İnsan kaynakları',
    'İşe alım',
    'Performans yönetimi',
    'Lojistik',
    'Depo yönetimi',
    'Tedarik zinciri',
    'Satın alma',
    'Müşteri ilişkileri',
    'Müşteri hizmetleri',
    'Dış ticaret',
    'İhracat',
    'İthalat',
    'Gümrük',
    'E-ticaret',
    'Grafik tasarım',
    'Ürün tasarımı',
    'İngilizce',
    'Almanca',
    'Arapça',
    'Fransızca',
    'Rusça',
    'İspanyolca',
    'Sunum',
    'Raporlama',
    'Veri analizi',
    'İş geliştirme',
    'Kurumsal satış',
    'Perakende',
    'Şantiye yönetimi',
    'Kalite kontrol',
    'İş sağlığı ve güvenliği',
    'Bakım onarım',
    'Kaynak',
    'Elektrik tesisatı',
    'Tesisat',
    'Sürücü belgesi',
    'Forklift',
    'Stok takibi',
  ],
  en: [
    'Sales',
    'Sales management',
    'Field sales',
    'Inside sales',
    'Marketing',
    'Digital marketing',
    'Content marketing',
    'Brand management',
    'Negotiation',
    'Project management',
    'Product management',
    'Accounting',
    'Finance',
    'Budgeting',
    'Financial analysis',
    'Human resources',
    'Recruiting',
    'Performance management',
    'Logistics',
    'Warehouse management',
    'Supply chain',
    'Procurement',
    'Customer relations',
    'Customer service',
    'International trade',
    'Export',
    'Import',
    'Customs',
    'E-commerce',
    'Graphic design',
    'Product design',
    'English',
    'German',
    'Arabic',
    'French',
    'Presentation',
    'Reporting',
    'Data analysis',
    'Business development',
    'Retail',
    'Quality control',
    'Health and safety',
    'Maintenance',
    'Inventory',
  ],
  de: [
    'Vertrieb',
    'Verkaufsleitung',
    'Außendienst',
    'Innendienst',
    'Marketing',
    'Digitales Marketing',
    'Verhandlung',
    'Projektmanagement',
    'Buchhaltung',
    'Finanzen',
    'Personalwesen',
    'Logistik',
    'Einkauf',
    'Kundenbeziehungen',
    'Kundenservice',
    'Außenhandel',
    'Export',
    'Import',
    'E-Commerce',
    'Grafikdesign',
    'Englisch',
    'Deutsch',
    'Präsentation',
    'Berichtswesen',
    'Datenanalyse',
    'Geschäftsentwicklung',
    'Qualitätssicherung',
    'Arbeitsschutz',
    'Wartung',
  ],
  es: [
    'Ventas',
    'Dirección comercial',
    'Ventas de campo',
    'Marketing',
    'Marketing digital',
    'Negociación',
    'Gestión de proyectos',
    'Contabilidad',
    'Finanzas',
    'Recursos humanos',
    'Logística',
    'Compras',
    'Atención al cliente',
    'Comercio exterior',
    'Exportación',
    'Importación',
    'Comercio electrónico',
    'Diseño gráfico',
    'Inglés',
    'Español',
    'Presentación',
    'Informes',
    'Análisis de datos',
    'Desarrollo de negocio',
    'Control de calidad',
    'Prevención de riesgos',
    'Mantenimiento',
  ],
  fr: [
    'Vente',
    'Direction commerciale',
    'Vente terrain',
    'Marketing',
    'Marketing digital',
    'Négociation',
    'Gestion de projet',
    'Comptabilité',
    'Finance',
    'Ressources humaines',
    'Logistique',
    'Achats',
    'Relation client',
    'Commerce international',
    'Export',
    'Import',
    'E-commerce',
    'Graphisme',
    'Anglais',
    'Français',
    'Présentation',
    'Reporting',
    'Analyse de données',
    'Développement commercial',
    'Contrôle qualité',
    'Sécurité au travail',
    'Maintenance',
  ],
  ar: [
    'مبيعات',
    'إدارة المبيعات',
    'مبيعات ميدانية',
    'تسويق',
    'تسويق رقمي',
    'تفاوض',
    'إدارة المشاريع',
    'محاسبة',
    'مالية',
    'موارد بشرية',
    'لوجستيات',
    'مشتريات',
    'خدمة العملاء',
    'تجارة خارجية',
    'تصدير',
    'استيراد',
    'تجارة إلكترونية',
    'تصميم جرافيك',
    'الإنجليزية',
    'العربية',
    'عروض تقديمية',
    'تقارير',
    'تحليل بيانات',
    'تطوير الأعمال',
    'رقابة الجودة',
    'السلامة المهنية',
    'صيانة',
  ],
};

const POSITION_EXAMPLES: Record<SupportedLocale, string[]> = {
  tr: [
    'Satış Müdürü',
    'Satış Temsilcisi',
    'Satış Danışmanı',
    'Satış Uzmanı',
    'Bölge Satış Müdürü',
    'Kurumsal Satış Uzmanı',
    'İç Satış Temsilcisi',
    'Yazılım Geliştirici',
    'Kıdemli Yazılım Geliştirici',
    'Ön Yüz Geliştirici',
    'Arka Yüz Geliştirici',
    'Tam Yığın Geliştirici',
    'Yazılım Mimarı',
    'Mobil Uygulama Geliştirici',
    'Veri Analisti',
    'İş Analisti',
    'Sistem Analisti',
    'Muhasebe Uzmanı',
    'Muhasebe Müdürü',
    'Mali İşler Müdürü',
    'Finans Uzmanı',
    'Finans Müdürü',
    'Operasyon Müdürü',
    'Operasyon Uzmanı',
    'Pazarlama Uzmanı',
    'Pazarlama Müdürü',
    'Dijital Pazarlama Uzmanı',
    'Sosyal Medya Uzmanı',
    'İnsan Kaynakları Uzmanı',
    'İnsan Kaynakları Müdürü',
    'İşe Alım Uzmanı',
    'Proje Yöneticisi',
    'Ürün Yöneticisi',
    'Lojistik Uzmanı',
    'Lojistik Müdürü',
    'Depo Sorumlusu',
    'Depo Müdürü',
    'Satın Alma Uzmanı',
    'Satın Alma Müdürü',
    'Tedarik Zinciri Uzmanı',
    'Müşteri Temsilcisi',
    'Müşteri Hizmetleri Uzmanı',
    'Çağrı Merkezi Temsilcisi',
    'Grafik Tasarımcı',
    'UI/UX Tasarımcı',
    'İçerik Editörü',
    'İhracat Uzmanı',
    'İthalat Uzmanı',
    'Dış Ticaret Uzmanı',
    'Gümrük Müşaviri',
    'Şoför',
    'Ağır Vasıta Şoförü',
    'Forklift Operatörü',
    'Teknisyen',
    'Elektrik Teknisyeni',
    'Makine Teknisyeni',
    'Bakım Teknisyeni',
    'Usta',
    'Kalfa',
    'Şantiye Şefi',
    'İnşaat Mühendisi',
    'Makine Mühendisi',
    'Elektrik Mühendisi',
    'Endüstri Mühendisi',
    'Kalite Kontrol Uzmanı',
    'Kalite Müdürü',
    'İş Geliştirme Uzmanı',
    'Genel Müdür',
    'Genel Müdür Yardımcısı',
    'Şube Müdürü',
    'Mağaza Müdürü',
    'Mağaza Satış Danışmanı',
    'Asistan',
    'Yönetici Asistanı',
    'Ofis Personeli',
    'Sekreter',
    'Öğretmen',
    'Hemşire',
    'Eczacı',
    'Avukat',
    'Danışman',
    'Stajyer',
  ],
  en: [
    'Sales Manager',
    'Sales Representative',
    'Sales Consultant',
    'Account Manager',
    'Regional Sales Manager',
    'Software Developer',
    'Senior Software Developer',
    'Frontend Developer',
    'Backend Developer',
    'Full Stack Developer',
    'Mobile Developer',
    'Data Analyst',
    'Business Analyst',
    'Accountant',
    'Finance Manager',
    'Operations Manager',
    'Marketing Specialist',
    'Digital Marketing Specialist',
    'HR Specialist',
    'HR Manager',
    'Recruiter',
    'Project Manager',
    'Product Manager',
    'Logistics Specialist',
    'Warehouse Manager',
    'Procurement Specialist',
    'Customer Support',
    'Graphic Designer',
    'UI/UX Designer',
    'Export Specialist',
    'Import Specialist',
    'Driver',
    'Technician',
    'Maintenance Technician',
    'Site Supervisor',
    'Civil Engineer',
    'Mechanical Engineer',
    'Electrical Engineer',
    'Quality Control Specialist',
    'Business Development',
    'General Manager',
    'Store Manager',
    'Assistant',
    'Teacher',
    'Nurse',
    'Lawyer',
    'Consultant',
    'Intern',
  ],
  de: [
    'Vertriebsleiter',
    'Vertriebsmitarbeiter',
    'Key Account Manager',
    'Softwareentwickler',
    'Frontend-Entwickler',
    'Backend-Entwickler',
    'Datenanalyst',
    'Business Analyst',
    'Buchhalter',
    'Finanzleiter',
    'Betriebsleiter',
    'Marketing-Spezialist',
    'HR-Spezialist',
    'Projektleiter',
    'Produktmanager',
    'Logistik-Spezialist',
    'Lagerleiter',
    'Einkäufer',
    'Kundenberater',
    'Grafikdesigner',
    'Export-Sachbearbeiter',
    'Techniker',
    'Bauleiter',
    'Qualitätsmanager',
    'Geschäftsführer',
    'Filialleiter',
    'Assistent',
    'Lehrer',
    'Krankenpfleger',
    'Rechtsanwalt',
    'Berater',
    'Praktikant',
  ],
  es: [
    'Director de ventas',
    'Representante de ventas',
    'Account Manager',
    'Desarrollador de software',
    'Analista de datos',
    'Analista de negocio',
    'Contable',
    'Director financiero',
    'Director de operaciones',
    'Especialista en marketing',
    'Especialista en RR. HH.',
    'Jefe de proyecto',
    'Product Manager',
    'Especialista en logística',
    'Jefe de almacén',
    'Especialista en compras',
    'Atención al cliente',
    'Diseñador gráfico',
    'Especialista de exportación',
    'Técnico',
    'Jefe de obra',
    'Control de calidad',
    'Director general',
    'Gerente de tienda',
    'Asistente',
    'Profesor',
    'Enfermero',
    'Abogado',
    'Consultor',
    'Becario',
  ],
  fr: [
    'Directeur commercial',
    'Commercial',
    'Account Manager',
    'Développeur logiciel',
    'Analyste de données',
    'Analyste métier',
    'Comptable',
    'Directeur financier',
    'Directeur des opérations',
    'Spécialiste marketing',
    'Spécialiste RH',
    'Chef de projet',
    'Product Manager',
    'Spécialiste logistique',
    'Chef d’entrepôt',
    'Acheteur',
    'Service client',
    'Graphiste',
    'Chargé d’export',
    'Technicien',
    'Chef de chantier',
    'Contrôleur qualité',
    'Directeur général',
    'Directeur de magasin',
    'Assistant',
    'Enseignant',
    'Infirmier',
    'Avocat',
    'Consultant',
    'Stagiaire',
  ],
  ar: [
    'مدير مبيعات',
    'مندوب مبيعات',
    'مدير حسابات',
    'مطور برمجيات',
    'محلل بيانات',
    'محلل أعمال',
    'محاسب',
    'مدير مالي',
    'مدير عمليات',
    'أخصائي تسويق',
    'أخصائي موارد بشرية',
    'مدير مشروع',
    'مدير منتج',
    'أخصائي لوجستيات',
    'مدير مستودع',
    'أخصائي مشتريات',
    'خدمة العملاء',
    'مصمم جرافيك',
    'أخصائي تصدير',
    'فني',
    'مهندس موقع',
    'مراقب جودة',
    'مدير عام',
    'مدير متجر',
    'مساعد',
    'معلم',
    'ممرض',
    'محام',
    'مستشار',
    'متدرب',
  ],
};

const TR_CITIES = [
  'Adana',
  'Adıyaman',
  'Afyonkarahisar',
  'Ağrı',
  'Amasya',
  'Ankara',
  'Antalya',
  'Artvin',
  'Aydın',
  'Balıkesir',
  'Bilecik',
  'Bingöl',
  'Bitlis',
  'Bolu',
  'Burdur',
  'Bursa',
  'Çanakkale',
  'Çankırı',
  'Çorum',
  'Denizli',
  'Diyarbakır',
  'Edirne',
  'Elazığ',
  'Erzincan',
  'Erzurum',
  'Eskişehir',
  'Gaziantep',
  'Giresun',
  'Gümüşhane',
  'Hakkâri',
  'Hatay',
  'Isparta',
  'Mersin',
  'İstanbul',
  'İzmir',
  'Kars',
  'Kastamonu',
  'Kayseri',
  'Kırklareli',
  'Kırşehir',
  'Kocaeli',
  'Konya',
  'Kütahya',
  'Malatya',
  'Manisa',
  'Kahramanmaraş',
  'Mardin',
  'Muğla',
  'Muş',
  'Nevşehir',
  'Niğde',
  'Ordu',
  'Rize',
  'Sakarya',
  'Samsun',
  'Siirt',
  'Sinop',
  'Sivas',
  'Tekirdağ',
  'Tokat',
  'Trabzon',
  'Tunceli',
  'Şanlıurfa',
  'Uşak',
  'Van',
  'Yozgat',
  'Zonguldak',
  'Aksaray',
  'Bayburt',
  'Karaman',
  'Kırıkkale',
  'Batman',
  'Şırnak',
  'Bartın',
  'Ardahan',
  'Iğdır',
  'Yalova',
  'Karabük',
  'Kilis',
  'Osmaniye',
  'Düzce',
];

const WORLD_CITIES = [
  'London',
  'Berlin',
  'Paris',
  'Madrid',
  'Barcelona',
  'Amsterdam',
  'Dubai',
  'Abu Dhabi',
  'Riyadh',
  'Doha',
  'Cairo',
  'New York',
  'Los Angeles',
  'Singapore',
  'Hong Kong',
  'Tokyo',
  'Mumbai',
  'São Paulo',
  'Vienna',
  'Zurich',
  'Brussels',
  'Rome',
  'Milan',
  'Munich',
  'Hamburg',
  'Frankfurt',
];

const SCHOOLS = [
  'Boğaziçi Üniversitesi',
  'Orta Doğu Teknik Üniversitesi',
  'İstanbul Teknik Üniversitesi',
  'İstanbul Üniversitesi',
  'Ankara Üniversitesi',
  'Hacettepe Üniversitesi',
  'Ege Üniversitesi',
  'Dokuz Eylül Üniversitesi',
  'Gazi Üniversitesi',
  'Yıldız Teknik Üniversitesi',
  'Marmara Üniversitesi',
  'Koç Üniversitesi',
  'Sabancı Üniversitesi',
  'Bilkent Üniversitesi',
  'Özyeğin Üniversitesi',
  'Bahçeşehir Üniversitesi',
  'Galatasaray Üniversitesi',
  'Mimar Sinan Güzel Sanatlar Üniversitesi',
  'Anadolu Üniversitesi',
  'Akdeniz Üniversitesi',
  'Çukurova Üniversitesi',
  'Karadeniz Teknik Üniversitesi',
  'Atatürk Üniversitesi',
  'Selçuk Üniversitesi',
  'Bursa Uludağ Üniversitesi',
  'Erciyes Üniversitesi',
  'Kocaeli Üniversitesi',
  'Sakarya Üniversitesi',
  'Gebze Teknik Üniversitesi',
  'TOBB Ekonomi ve Teknoloji Üniversitesi',
  'TED Üniversitesi',
  'Başkent Üniversitesi',
  'Çankaya Üniversitesi',
  'Atılım Üniversitesi',
  'Yeditepe Üniversitesi',
  'İstanbul Bilgi Üniversitesi',
  'Kadir Has Üniversitesi',
  'Işık Üniversitesi',
  'MEF Üniversitesi',
  'Medipol Üniversitesi',
  'Üsküdar Üniversitesi',
  'Beykent Üniversitesi',
  'İstanbul Aydın Üniversitesi',
  'İstanbul Kültür Üniversitesi',
  'Nişantaşı Üniversitesi',
  'Piri Reis Üniversitesi',
  'Haliç Üniversitesi',
  'Fatih Sultan Mehmet Vakıf Üniversitesi',
  'İstanbul Gelişim Üniversitesi',
  'Altınbaş Üniversitesi',
  'İstanbul Ticaret Üniversitesi',
  'İzmir Yüksek Teknoloji Enstitüsü',
  'İzmir Ekonomi Üniversitesi',
  'Yaşar Üniversitesi',
  'Eskişehir Osmangazi Üniversitesi',
  'Süleyman Demirel Üniversitesi',
  'Pamukkale Üniversitesi',
  'Ondokuz Mayıs Üniversitesi',
  'İnönü Üniversitesi',
  'Fırat Üniversitesi',
  'Dicle Üniversitesi',
  'Gaziantep Üniversitesi',
  'Mersin Üniversitesi',
  'Çanakkale Onsekiz Mart Üniversitesi',
  'Trakya Üniversitesi',
  'Namık Kemal Üniversitesi',
  'Anadolu Lisesi',
  'Fen Lisesi',
  'Mesleki ve Teknik Anadolu Lisesi',
  'İmam Hatip Lisesi',
  'Özel Lise',
  'Açık Öğretim Lisesi',
  'Meslek Yüksekokulu',
  'Anadolu Üniversitesi Açıköğretim Fakültesi',
  'Harvard University',
  'MIT',
  'Stanford University',
  'University of Oxford',
  'University of Cambridge',
  'ETH Zurich',
  'TU Munich',
  'Sorbonne University',
];

const DEGREE_EXAMPLES: Record<SupportedLocale, string[]> = {
  tr: [
    'Lise Diploması',
    'Anadolu Lisesi Diploması',
    'Fen Lisesi Diploması',
    'Meslek Lisesi Diploması',
    'Ön Lisans',
    'Lisans',
    'Yüksek Lisans',
    'Doktora',
    'Doçentlik',
    'Profesörlük',
    'MBA',
    'Executive MBA',
    'Tezsiz Yüksek Lisans',
    'Tezli Yüksek Lisans',
    'Sertifika',
    'Uzmanlık',
    'Meslek Yüksekokulu',
    'Açıköğretim Lisans',
    'Açıköğretim Ön Lisans',
    'Çift Anadal',
    'Yan Dal',
    'Hazırlık',
    'Associate Degree',
    'Bachelor',
    'Master',
    'PhD',
  ],
  en: [
    'High school diploma',
    'Associate degree',
    'Bachelor’s degree',
    'Master’s degree',
    'Doctorate',
    'MBA',
    'Executive MBA',
    'Certificate',
    'Vocational diploma',
    'Open education bachelor',
    'Double major',
    'Minor',
    'PhD',
  ],
  de: [
    'Abitur',
    'Realschulabschluss',
    'Ausbildung',
    'Bachelor',
    'Master',
    'Diplom',
    'Promotion',
    'MBA',
    'Zertifikat',
    'Fachhochschulabschluss',
  ],
  es: [
    'Bachillerato',
    'Técnico',
    'Grado',
    'Máster',
    'Doctorado',
    'MBA',
    'Certificado',
    'Formación profesional',
  ],
  fr: [
    'Baccalauréat',
    'BTS',
    'DUT',
    'Licence',
    'Master',
    'Doctorat',
    'MBA',
    'Certificat',
    'Diplôme d’ingénieur',
  ],
  ar: [
    'شهادة ثانوية',
    'دبلوم',
    'بكالوريوس',
    'ماجستير',
    'دكتوراه',
    'MBA',
    'شهادة مهنية',
  ],
};

const FIELD_EXAMPLES: Record<SupportedLocale, string[]> = {
  tr: [
    'Bilgisayar Mühendisliği',
    'Yazılım Mühendisliği',
    'Yönetim Bilişim Sistemleri',
    'Bilgisayar Programcılığı',
    'Endüstri Mühendisliği',
    'Makine Mühendisliği',
    'Elektrik-Elektronik Mühendisliği',
    'Elektrik Mühendisliği',
    'Elektronik ve Haberleşme Mühendisliği',
    'İnşaat Mühendisliği',
    'Mimarlık',
    'İç Mimarlık',
    'Endüstriyel Tasarım',
    'Harita Mühendisliği',
    'Çevre Mühendisliği',
    'Gıda Mühendisliği',
    'Kimya Mühendisliği',
    'Metalurji ve Malzeme Mühendisliği',
    'Petrol ve Doğalgaz Mühendisliği',
    'Uçak Mühendisliği',
    'Otomotiv Mühendisliği',
    'Mekatronik Mühendisliği',
    'İşletme',
    'İktisat',
    'Maliye',
    'Çalışma Ekonomisi',
    'Uluslararası Ticaret',
    'Uluslararası İlişkiler',
    'Siyaset Bilimi ve Kamu Yönetimi',
    'Hukuk',
    'Muhasebe ve Finans Yönetimi',
    'Bankacılık ve Sigortacılık',
    'Pazarlama',
    'İnsan Kaynakları Yönetimi',
    'Lojistik',
    'Turizm İşletmeciliği',
    'Tıp',
    'Diş Hekimliği',
    'Eczacılık',
    'Hemşirelik',
    'Ebelik',
    'Fizyoterapi ve Rehabilitasyon',
    'Veterinerlik',
    'Psikoloji',
    'Sosyoloji',
    'Rehberlik ve Psikolojik Danışmanlık',
    'İletişim',
    'Halkla İlişkiler ve Tanıtım',
    'Gazetecilik',
    'Radyo Televizyon ve Sinema',
    'Grafik Tasarım',
    'Görsel İletişim Tasarımı',
    'İngilizce Öğretmenliği',
    'Sınıf Öğretmenliği',
    'Okul Öncesi Öğretmenliği',
    'Matematik',
    'Fizik',
    'Kimya',
    'Biyoloji',
    'Tarih',
    'Türk Dili ve Edebiyatı',
    'Ziraat Mühendisliği',
    'Orman Mühendisliği',
    'Güzel Sanatlar',
    'Müzik',
    'Spor Bilimleri',
    'Siber Güvenlik',
    'Yapay Zeka',
    'Veri Bilimi',
    'Web Tasarım ve Kodlama',
  ],
  en: [
    'Computer Engineering',
    'Software Engineering',
    'Information Systems',
    'Computer Programming',
    'Industrial Engineering',
    'Mechanical Engineering',
    'Electrical Engineering',
    'Civil Engineering',
    'Architecture',
    'Interior Architecture',
    'Business Administration',
    'Economics',
    'Finance',
    'International Trade',
    'International Relations',
    'Law',
    'Accounting',
    'Marketing',
    'Human Resources',
    'Logistics',
    'Medicine',
    'Dentistry',
    'Pharmacy',
    'Nursing',
    'Psychology',
    'Sociology',
    'Communication',
    'Graphic Design',
    'English Teaching',
    'Mathematics',
    'Physics',
    'Chemistry',
    'Biology',
    'History',
    'Cybersecurity',
    'Artificial Intelligence',
    'Data Science',
  ],
  de: [
    'Informatik',
    'Softwaretechnik',
    'Wirtschaftsinformatik',
    'Maschinenbau',
    'Elektrotechnik',
    'Bauingenieurwesen',
    'Architektur',
    'Betriebswirtschaft',
    'Volkswirtschaft',
    'Rechtswissenschaft',
    'Rechnungswesen',
    'Marketing',
    'Personalwesen',
    'Logistik',
    'Medizin',
    'Pflege',
    'Psychologie',
    'Soziologie',
    'Kommunikationswissenschaft',
    'Grafikdesign',
    'Mathematik',
    'Physik',
    'Chemie',
    'Cybersicherheit',
    'Künstliche Intelligenz',
    'Datenwissenschaft',
  ],
  es: [
    'Ingeniería informática',
    'Ingeniería de software',
    'Ingeniería industrial',
    'Ingeniería mecánica',
    'Ingeniería civil',
    'Arquitectura',
    'Administración de empresas',
    'Economía',
    'Derecho',
    'Contabilidad',
    'Marketing',
    'Recursos humanos',
    'Logística',
    'Medicina',
    'Enfermería',
    'Psicología',
    'Sociología',
    'Comunicación',
    'Diseño gráfico',
    'Matemáticas',
    'Ciberseguridad',
    'Inteligencia artificial',
    'Ciencia de datos',
  ],
  fr: [
    'Informatique',
    'Génie logiciel',
    'Génie industriel',
    'Génie mécanique',
    'Génie civil',
    'Architecture',
    'Gestion',
    'Économie',
    'Droit',
    'Comptabilité',
    'Marketing',
    'Ressources humaines',
    'Logistique',
    'Médecine',
    'Soins infirmiers',
    'Psychologie',
    'Sociologie',
    'Communication',
    'Graphisme',
    'Mathématiques',
    'Cybersécurité',
    'Intelligence artificielle',
    'Science des données',
  ],
  ar: [
    'هندسة حاسوب',
    'هندسة برمجيات',
    'هندسة صناعية',
    'هندسة ميكانيكية',
    'هندسة مدنية',
    'عمارة',
    'إدارة أعمال',
    'اقتصاد',
    'قانون',
    'محاسبة',
    'تسويق',
    'موارد بشرية',
    'لوجستيات',
    'طب',
    'تمريض',
    'علم نفس',
    'علم اجتماع',
    'اتصال',
    'تصميم جرافيك',
    'رياضيات',
    'أمن سيبراني',
    'ذكاء اصطناعي',
    'علم بيانات',
  ],
};

const CITY_EXAMPLES: Record<SupportedLocale, string[]> = {
  tr: [...TR_CITIES, ...EXTRA_DISTRICTS_TR],
  en: ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Antalya', ...WORLD_CITIES, ...EXTRA_WORLD_CITIES],
  de: [
    'Istanbul',
    'Ankara',
    'Izmir',
    'Berlin',
    'München',
    'Hamburg',
    'Frankfurt',
    'Köln',
    'Wien',
    'Zürich',
    ...WORLD_CITIES,
    ...EXTRA_WORLD_CITIES,
  ],
  es: [
    'Estambul',
    'Ankara',
    'Esmirna',
    'Madrid',
    'Barcelona',
    'Valencia',
    'Sevilla',
    'Ciudad de México',
    'Buenos Aires',
    ...WORLD_CITIES,
    ...EXTRA_WORLD_CITIES,
  ],
  fr: [
    'Istanbul',
    'Ankara',
    'Izmir',
    'Paris',
    'Lyon',
    'Marseille',
    'Toulouse',
    'Bruxelles',
    'Genève',
    ...WORLD_CITIES,
    ...EXTRA_WORLD_CITIES,
  ],
  ar: [
    'إسطنبول',
    'أنقرة',
    'إزمير',
    'دبي',
    'الرياض',
    'الدوحة',
    'القاهرة',
    'عمّان',
    'بيروت',
    ...WORLD_CITIES,
    ...EXTRA_WORLD_CITIES,
  ],
};

export function careerExamples(kind: CareerExampleKind, locale: SupportedLocale): string[] {
  if (kind === 'position') {
    const extras = locale === 'tr' ? EXTRA_POSITIONS_TR : EXTRA_POSITIONS_EN;
    return uniqueNames([...POSITION_EXAMPLES[locale], ...extras], locale, '', 400);
  }
  if (kind === 'city') return uniqueNames(CITY_EXAMPLES[locale], locale, '', 400);
  if (kind === 'school') return uniqueNames([...SCHOOLS, ...EXTRA_SCHOOLS], locale, '', 400);
  if (kind === 'degree') {
    const extras = locale === 'tr' ? EXTRA_DEGREES_TR : [];
    return uniqueNames([...DEGREE_EXAMPLES[locale], ...extras], locale, '', 200);
  }
  if (kind === 'field') {
    const extras = locale === 'tr' ? EXTRA_FIELDS_TR : EXTRA_FIELDS_EN;
    return uniqueNames([...FIELD_EXAMPLES[locale], ...extras], locale, '', 400);
  }
  const localeSkills = locale === 'tr' ? EXTRA_SKILLS_TR : EXTRA_SKILLS_EN;
  return uniqueNames(
    [...SHARED_SKILLS, ...EXTRA_SHARED_SKILLS, ...LOCALE_SKILLS[locale], ...localeSkills],
    locale,
    '',
    400,
  );
}

export function filterSuggestions(items: string[], query: string, locale = 'tr', limit = LIST_LIMIT): string[] {
  const needle = query.trim().toLocaleLowerCase(locale);
  if (!needle) return items.slice(0, limit);

  const ranked = items
    .map((item) => {
      const hay = item.toLocaleLowerCase(locale);
      if (hay === needle) return { item, rank: 0 };
      if (hay.startsWith(needle)) return { item, rank: 1 };
      if (hay.includes(needle)) return { item, rank: 2 };
      return null;
    })
    .filter((row): row is { item: string; rank: number } => row !== null)
    .sort((a, b) => a.rank - b.rank || a.item.localeCompare(b.item, locale));

  return ranked.slice(0, limit).map((row) => row.item);
}

/** Katalog her zaman görünür; platformdaki adlar varsa öne eklenir. */
export function mergeSuggestions(
  remote: string[] | undefined,
  fallback: string[],
  query: string,
  limit = LIST_LIMIT,
  locale = 'tr',
): string[] {
  return uniqueNames([...(remote ?? []), ...fallback], locale, query, limit);
}

function uniqueNames(items: string[], locale: string, query = '', limit = 80): string[] {
  const seen = new Set<string>();
  const unique: string[] = [];
  for (const item of items) {
    const key = item.trim().toLocaleLowerCase(locale);
    if (!item.trim() || seen.has(key)) continue;
    seen.add(key);
    unique.push(item.trim());
  }
  return filterSuggestions(unique, query, locale, limit);
}
