/** Birinci dosyadaki çekirdek listenin üzerine binen ek örnekler. */

export const EXTRA_SHARED_SKILLS = [
  'Microsoft Project',
  'Microsoft Visio',
  'Microsoft Dynamics',
  'Microsoft SQL Server',
  'Excel VBA',
  'Pivot Table',
  'Power Query',
  'Power Automate',
  'SharePoint',
  'OneDrive',
  'Google Sheets',
  'Google Docs',
  'Google Drive',
  'Looker Studio',
  'BigQuery',
  'Oracle',
  'SAP MM',
  'SAP FI',
  'SAP SD',
  'SAP PP',
  'SAP HANA',
  'Logo Tiger',
  'Logo Go',
  'Netsis',
  'Mikro',
  'Paraşüt',
  'BizimHesap',
  'Luca',
  'ETA',
  'Zirve',
  'e-Fatura',
  'e-Arşiv',
  'e-İrsaliye',
  'e-Defter',
  'QuickBooks',
  'Xero',
  'Odoo',
  'Zoho',
  'Pipedrive',
  'Monday.com',
  'Asana',
  'ClickUp',
  'Confluence',
  'Bitbucket',
  'GitHub',
  'GitLab',
  'Kubernetes',
  'AWS',
  'Google Cloud',
  'Firebase',
  'MongoDB',
  'Redis',
  'GraphQL',
  'REST API',
  'Vue.js',
  'Angular',
  'Next.js',
  'Flutter',
  'React Native',
  'Kotlin',
  'Swift',
  'Go',
  'Rust',
  'R',
  'MATLAB',
  'SPSS',
  'Stata',
  'SAS',
  'Python Pandas',
  'Machine Learning',
  'TensorFlow',
  'PyTorch',
  'ChatGPT',
  'Prompt engineering',
  'Unity',
  'Unreal Engine',
  'Blender',
  '3ds Max',
  'Maya',
  'Cinema 4D',
  'Rhino',
  'Grasshopper',
  'CATIA',
  'Siemens NX',
  'ANSYS',
  'ETABS',
  'SAP2000',
  'STAAD',
  'ArcGIS',
  'QGIS',
  'Primavera P6',
  'MS Project',
  'Trello',
  'Notion',
  'Airtable',
  'Mailchimp',
  'Klaviyo',
  'Hotjar',
  'Semrush',
  'Ahrefs',
  'TikTok Ads',
  'LinkedIn Ads',
  'YouTube Ads',
  'WordPress',
  'WooCommerce',
  'Magento',
  'PrestaShop',
  'Shopify',
  'IdeaSoft',
  'Ticimax',
  'Softtr',
  'Ikas',
  'Trendyol',
  'Hepsiburada',
  'Amazon',
  'N11',
  'Çiçeksepeti',
  'Getir',
  'Yemeksepeti',
  'WhatsApp Business',
  'Telegram',
  'CorelDRAW',
  'Lightroom',
  'DaVinci Resolve',
  'Final Cut Pro',
  'Ableton',
  'Pro Tools',
  'AutoCAD Civil 3D',
  'AutoCAD Mechanical',
  'Inventor',
  'Fusion 360',
  'EPLAN',
  'TIA Portal',
  'Siemens PLC',
  'Allen Bradley',
  'SCADA',
  'HMI',
  'CNC Programlama',
  'Mastercam',
  'SolidCAM',
  'ISO 14001',
  'ISO 45001',
  'ISO 27001',
  'HACCP',
  'GMP',
  '5S',
  'Kanban',
  'ITIL',
  'PMP',
  'PRINCE2',
  'COBIT',
  'TOGAF',
  'CISSP',
  'CEH',
  'CompTIA',
  'CCNA',
  'AWS Certified',
  'Azure Administrator',
];

export const EXTRA_SKILLS_TR = [
  'Telefonla satış',
  'Soğuk arama',
  'Teklif hazırlama',
  'Fiyatlandırma',
  'İhale takibi',
  'Keşif',
  'Sözleşme yönetimi',
  'Tedarikçi yönetimi',
  'Stok sayımı',
  'Sevkiyat planlama',
  'Rota planlama',
  'Filo yönetimi',
  'Gümrükleme',
  'Menşe belgesi',
  'Beşeri ihracat',
  'Akreditif',
  'Incoterms',
  'Kambiyo',
  'Bordro',
  'SGK bildirimi',
  'Muhtasar',
  'KDV beyannamesi',
  'Kurumlar vergisi',
  'Bağımsız denetim',
  'İç denetim',
  'Maliyet muhasebesi',
  'Bütçe kontrol',
  'Nakit akışı',
  'Tahsilat',
  'Cari hesap',
  'Çek senet',
  'Kredi takibi',
  'Sigorta poliçesi',
  'Hasar dosyası',
  'Emlak danışmanlığı',
  'Tapu işlemleri',
  'Kat karşılığı',
  'Şantiye koordinasyonu',
  'Metraj',
  'Keşif özeti',
  'Hakediş',
  'Yapı denetim',
  'İskan',
  'Ruhsat',
  'Yangın güvenliği',
  'İş güvenliği uzmanlığı',
  'OSGB',
  'Risk değerlendirme',
  'Acil durum planı',
  'Kaynak (MIG)',
  'Kaynak (TIG)',
  'Kaynak (elektrod)',
  'Tornacılık',
  'Tesviye',
  'Freze',
  'Kalıpçılık',
  'Pres operatörlüğü',
  'Boya',
  'Sıva',
  'Alçıpan',
  'Fayans',
  'Seramik',
  'Marangozluk',
  'Mobilya montajı',
  'Doğalgaz tesisatı',
  'Kalorifer',
  'Klima montajı',
  'Kombi servisi',
  'Elektrik pano',
  'Zayıf akım',
  'Kamera sistemi',
  'Yangın algılama',
  'Asansör bakımı',
  'Forklift ehliyeti',
  'Vinç operatörlüğü',
  'SRC belgesi',
  'ADR belgesi',
  'Ehliyet B',
  'Ehliyet C',
  'Ehliyet E',
  'Ehliyet D',
  'Aşçılık',
  'Pastacılık',
  'Barista',
  'Servis',
  'Kat hizmetleri',
  'Ön büro',
  'Rezervasyon',
  'Çeviri',
  'Simultane çeviri',
  'Diksiyon',
  'Eğitmenlik',
  'Koçluk',
  'Mentörlük',
  'Kürtçe',
  'Zazaca',
  'Osmanlıca',
  'Japonca',
  'Çince',
  'Korece',
  'İtalyanca',
  'Portekizce',
  'Hollandaca',
  'Farsça',
  'İbranice',
  'Ukraynaca',
  'Lehçe',
];

export const EXTRA_POSITIONS_TR = [
  'Satış Koordinatörü',
  'Satış Destek Uzmanı',
  'Bayi Müdürü',
  'Kanal Satış Uzmanı',
  'Key Account Manager',
  'Telesatış Temsilcisi',
  'E-ticaret Operasyon Uzmanı',
  'E-ticaret Müdürü',
  'Pazarlama Koordinatörü',
  'Marka Müdürü',
  'Ürün Uzmanı',
  'Kategori Müdürü',
  'Ticaret Müdürü',
  'İhracat Müdürü',
  'İthalat Müdürü',
  'Gümrük Uzmanı',
  'Planlama Uzmanı',
  'Üretim Planlama Uzmanı',
  'Üretim Mühendisi',
  'Üretim Müdürü',
  'Vardiya Amiri',
  'Usta Başı',
  'Kalite Mühendisi',
  'Ar-Ge Mühendisi',
  'Ar-Ge Uzmanı',
  'Proses Mühendisi',
  'Bakım Mühendisi',
  'Bakım Müdürü',
  'Elektrik Bakım Teknisyeni',
  'Mekanik Bakım Teknisyeni',
  'Otomasyon Teknisyeni',
  'PLC Teknisyeni',
  'CNC Operatörü',
  'CNC Programcısı',
  'Tornacı',
  'Tesviyeci',
  'Kaynakçı',
  'Kaynak Ustası',
  'Kalıpçı',
  'Pres Operatörü',
  'Paketleme Elemanı',
  'Sevkiyat Elemanı',
  'Sevkiyat Sorumlusu',
  'Depo Elemanı',
  'Depo Sevkiyat Sorumlusu',
  'Stok Kontrol Uzmanı',
  'Envanter Uzmanı',
  'Satın Alma Elemanı',
  'Tedarikçi Geliştirme Uzmanı',
  'Mali Müşavir',
  'SMMM',
  'Muhasebe Elemanı',
  'Bordro Uzmanı',
  'Ön Muhasebe Elemanı',
  'Veznedar',
  'Gişe Yetkilisi',
  'Bireysel Bankacılık Yetkilisi',
  'Kurumsal Şube Yetkilisi',
  'Kredi Analisti',
  'Risk Analisti',
  'Aktüer',
  'Sigorta Uzmanı',
  'Hasar Uzmanı',
  'Emlak Danışmanı',
  'Gayrimenkul Uzmanı',
  'İnşaat Teknikeri',
  'Mimar',
  'İç Mimar',
  'Şehir Plancısı',
  'Harita Teknisyeni',
  'Jeoloji Mühendisi',
  'Maden Mühendisi',
  'Ziraat Mühendisi',
  'Gıda Mühendisi',
  'Kimya Mühendisi',
  'Çevre Mühendisi',
  'Enerji Mühendisi',
  'Yazılım Test Uzmanı',
  'QA Engineer',
  'DevOps Mühendisi',
  'Sistem Yöneticisi',
  'Ağ Yöneticisi',
  'Siber Güvenlik Uzmanı',
  'Veri Bilimci',
  'Veri Mühendisi',
  'IT Destek Uzmanı',
  'Helpdesk',
  'Bilgi İşlem Sorumlusu',
  'ERP Danışmanı',
  'SAP Danışmanı',
  'İş Zekası Uzmanı',
  'SEO Uzmanı',
  'SEM Uzmanı',
  'İçerik Uzmanı',
  'Copywriter',
  'Topluluk Yöneticisi',
  'E-posta Pazarlama Uzmanı',
  'Fotoğrafçı',
  'Kameraman',
  'Video Editörü',
  'Ses Teknisyeni',
  'Çevirmen',
  'Editör',
  'Redaktör',
  'Öğretim Görevlisi',
  'Araştırma Görevlisi',
  'Okul Müdürü',
  'Müdür Yardımcısı',
  'Rehber Öğretmen',
  'İngilizce Öğretmeni',
  'Matematik Öğretmeni',
  'Sınıf Öğretmeni',
  'Antrenör',
  'Doktor',
  'Pratisyen Hekim',
  'Uzman Doktor',
  'Diş Hekimi',
  'Veteriner Hekim',
  'Ebe',
  'Sağlık Teknikeri',
  'Laborant',
  'Radyoloji Teknisyeni',
  'Eczane Teknikeri',
  'Paramedik',
  'Ambulans Şoförü',
  'Avukat',
  'Hukuk Müşaviri',
  'İcra Müdürü',
  'Kâtip',
  'Aşçı',
  'Aşçıbaşı',
  'Pastacı',
  'Garson',
  'Komi',
  'Barista',
  'Barmen',
  'Şef Garson',
  'Kat Görevlisi',
  'Ön Büro Yetkilisi',
  'Resepsiyonist',
  'Concierge',
  'Turist Rehberi',
  'Transfer Görevlisi',
  'Hostes',
  'Kabin Memuru',
  'Pilot',
  'Kaptan',
  'Gemiadamı',
  'Kurye',
  'Moto Kurye',
  'Kamyon Şoförü',
  'Tır Şoförü',
  'Servis Şoförü',
  'Taksi Şoförü',
  'Güvenlik Görevlisi',
  'Özel Güvenlik',
  'Temizlik Görevlisi',
  'Bahçıvan',
  'Teknik Servis Elemanı',
  'Müşteri İlişkileri Yöneticisi',
  'Şikayet Yönetimi Uzmanı',
  'Ofis Yöneticisi',
  'İdari İşler Uzmanı',
  'Satın Alma Asistanı',
  'İnsan Kaynakları Asistanı',
  'Pazarlama Asistanı',
  'Satış Asistanı',
  'Stajyer Mühendis',
  'Stajyer Avukat',
  'Part-time Eleman',
  'Kasiyer',
  'Reyon Görevlisi',
  'Tezgahtar',
  'Mağaza Görsel Düzenleme Uzmanı',
  'Depo Sayım Elemanı',
];

export const EXTRA_SCHOOLS = [
  'İstanbul Üniversitesi-Cerrahpaşa',
  'Sağlık Bilimleri Üniversitesi',
  'Milli Savunma Üniversitesi',
  'Polis Akademisi',
  'Türk-Alman Üniversitesi',
  'İstanbul Medeniyet Üniversitesi',
  'Yıldız Teknik Üniversitesi',
  'Marmara Üniversitesi',
  'Abdullah Gül Üniversitesi',
  'Konya Teknik Üniversitesi',
  'Necmettin Erbakan Üniversitesi',
  'Karamanoğlu Mehmetbey Üniversitesi',
  'Hitit Üniversitesi',
  'Zonguldak Bülent Ecevit Üniversitesi',
  'Recep Tayyip Erdoğan Üniversitesi',
  'Ordu Üniversitesi',
  'Giresun Üniversitesi',
  'Kastamonu Üniversitesi',
  'Sinop Üniversitesi',
  'Amasya Üniversitesi',
  'Tokat Gaziosmanpaşa Üniversitesi',
  'Yozgat Bozok Üniversitesi',
  'Kırıkkale Üniversitesi',
  'Kırşehir Ahi Evran Üniversitesi',
  'Nevşehir Hacı Bektaş Veli Üniversitesi',
  'Niğde Ömer Halisdemir Üniversitesi',
  'Aksaray Üniversitesi',
  'Osmaniye Korkut Ata Üniversitesi',
  'Kahramanmaraş Sütçü İmam Üniversitesi',
  'Kahramanmaraş İstiklal Üniversitesi',
  'Hatay Mustafa Kemal Üniversitesi',
  'İskenderun Teknik Üniversitesi',
  'Kilis 7 Aralık Üniversitesi',
  'Adıyaman Üniversitesi',
  'Şırnak Üniversitesi',
  'Hakkari Üniversitesi',
  'Muş Alparslan Üniversitesi',
  'Bitlis Eren Üniversitesi',
  'Bingöl Üniversitesi',
  'Munzur Üniversitesi',
  'Ardahan Üniversitesi',
  'Iğdır Üniversitesi',
  'Ağrı İbrahim Çeçen Üniversitesi',
  'Bayburt Üniversitesi',
  'Gümüşhane Üniversitesi',
  'Artvin Çoruh Üniversitesi',
  'Bolu Abant İzzet Baysal Üniversitesi',
  'Düzce Üniversitesi',
  'Yalova Üniversitesi',
  'Kırklareli Üniversitesi',
  'Tekirdağ Namık Kemal Üniversitesi',
  'Balıkesir Üniversitesi',
  'Bandırma Onyedi Eylül Üniversitesi',
  'Manisa Celal Bayar Üniversitesi',
  'Uşak Üniversitesi',
  'Afyon Kocatepe Üniversitesi',
  'Afyonkarahisar Sağlık Bilimleri Üniversitesi',
  'Kütahya Dumlupınar Üniversitesi',
  'Kütahya Sağlık Bilimleri Üniversitesi',
  'Bilecik Şeyh Edebali Üniversitesi',
  'Sivas Cumhuriyet Üniversitesi',
  'Sivas Bilim ve Teknoloji Üniversitesi',
  'Malatya Turgut Özal Üniversitesi',
  'Van Yüzüncü Yıl Üniversitesi',
  'Mardin Artuklu Üniversitesi',
  'Batman Üniversitesi',
  'Siirt Üniversitesi',
  'Harran Üniversitesi',
  'Hasan Kalyoncu Üniversitesi',
  'Sanko Üniversitesi',
  'Gaziantep İslam Bilim ve Teknoloji Üniversitesi',
  'Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi',
  'Toros Üniversitesi',
  'Tarsus Üniversitesi',
  'Alanya Alaaddin Keykubat Üniversitesi',
  'Antalya Bilim Üniversitesi',
  'Burdur Mehmet Akif Ersoy Üniversitesi',
  'Isparta Uygulamalı Bilimler Üniversitesi',
  'Aydın Adnan Menderes Üniversitesi',
  'Muğla Sıtkı Koçman Üniversitesi',
  'İzmir Kâtip Çelebi Üniversitesi',
  'İzmir Bakırçay Üniversitesi',
  'İzmir Demokrasi Üniversitesi',
  'İzmir Tınaztepe Üniversitesi',
  'Yaşar Üniversitesi',
  'Okan Üniversitesi',
  'Maltepe Üniversitesi',
  'Doğuş Üniversitesi',
  'Fenerbahçe Üniversitesi',
  'İstinye Üniversitesi',
  'Acıbadem Mehmet Ali Aydınlar Üniversitesi',
  'Bezmialem Vakıf Üniversitesi',
  'Biruni Üniversitesi',
  'İstanbul Sabahattin Zaim Üniversitesi',
  'İbn Haldun Üniversitesi',
  'Fatih Sultan Mehmet Vakıf Üniversitesi',
  '29 Mayıs Üniversitesi',
  'İstanbul Kent Üniversitesi',
  'İstanbul Topkapı Üniversitesi',
  'İstanbul Gedik Üniversitesi',
  'İstanbul Rumeli Üniversitesi',
  'İstanbul Yeni Yüzyıl Üniversitesi',
  'İstanbul Esenyurt Üniversitesi',
  'Beykoz Üniversitesi',
  'Çağ Üniversitesi',
  'Kapadokya Üniversitesi',
  'KTO Karatay Üniversitesi',
  'Konya Gıda ve Tarım Üniversitesi',
  'Ankara Sosyal Bilimler Üniversitesi',
  'Ankara Hacı Bayram Veli Üniversitesi',
  'Ankara Yıldırım Beyazıt Üniversitesi',
  'Ankara Bilim Üniversitesi',
  'Ankara Medipol Üniversitesi',
  'Lokman Hekim Üniversitesi',
  'Ufuk Üniversitesi',
  'Çankaya Üniversitesi',
  'THK Üniversitesi',
  'OSTİM Teknik Üniversitesi',
  'Türk Hava Kurumu Üniversitesi',
  'Gülhane',
  'Kara Harp Okulu',
  'Deniz Harp Okulu',
  'Hava Harp Okulu',
  'Jandarma ve Sahil Güvenlik Akademisi',
  'MEB Anadolu Lisesi',
  'MEB Fen Lisesi',
  'MEB Sosyal Bilimler Lisesi',
  'MEB Güzel Sanatlar Lisesi',
  'MEB Spor Lisesi',
  'Anadolu İmam Hatip Lisesi',
  'Çok Programlı Anadolu Lisesi',
  'Mesleki Eğitim Merkezi',
  'Halk Eğitim Merkezi',
  'Açıköğretim Fakültesi',
  'Atatürk Üniversitesi Açıköğretim Fakültesi',
  'İstanbul Üniversitesi Açık ve Uzaktan Eğitim Fakültesi',
  'Robert Kolej',
  'Üsküdar Amerikan Lisesi',
  'Tarsus Amerikan Koleji',
  'İzmir Amerikan Koleji',
  'Galatasaray Lisesi',
  'İstanbul Erkek Lisesi',
  'Kabataş Erkek Lisesi',
  'Cağaloğlu Anadolu Lisesi',
  'Vefa Lisesi',
  'Saint Joseph',
  'Saint Benoit',
  'Notre Dame de Sion',
  'Deutsche Schule Istanbul',
  'Özel TED Ankara Koleji',
  'Bilkent Erzurum Laboratuvar Okulu',
  'Koç Lisesi',
  'SEV Amerikan Koleji',
  'Imperial College London',
  'UCL',
  'LSE',
  'University of Edinburgh',
  'University of Manchester',
  'TU Delft',
  'KU Leuven',
  'Heidelberg University',
  'LMU Munich',
  'Sciences Po',
  'HEC Paris',
  'INSEAD',
  'Bocconi University',
  'IE University',
  'University of Toronto',
  'McGill University',
  'National University of Singapore',
  'Nanyang Technological University',
  'University of Tokyo',
  'Peking University',
  'Tsinghua University',
  'American University of Beirut',
  'King Saud University',
  'Khalifa University',
];

export const EXTRA_DEGREES_TR = [
  'İlkokul Diploması',
  'Ortaokul Diploması',
  'İlköğretim Diploması',
  'Sosyal Bilimler Lisesi Diploması',
  'Güzel Sanatlar Lisesi Diploması',
  'Spor Lisesi Diploması',
  'İmam Hatip Lisesi Diploması',
  'Açık Öğretim Lisesi Diploması',
  'Denklik Belgesi',
  'Yüksekokul Diploması',
  'Fakülte Diploması',
  'Mühendislik Diploması',
  'Eczacılık Diploması',
  'Diş Hekimliği Diploması',
  'Tıp Diploması',
  'Hukuk Diploması',
  'Eğitim Fakültesi Diploması',
  'Tıpta Uzmanlık',
  'Diş Hekimliğinde Uzmanlık',
  'Eczacılıkta Uzmanlık',
  'Bilim Uzmanlığı',
  'Sanatta Yeterlik',
  'Pedagojik Formasyon',
  'Öğretmenlik Sertifikası',
  'Yabancı Dil Hazırlık',
  'Çift Diploma',
  'Ortak Diploma',
  'Uzaktan Eğitim Lisans',
  'Uzaktan Eğitim Yüksek Lisans',
  'Yaz Okulu Sertifikası',
  'Mesleki Yeterlilik Belgesi',
  'MYK Seviye 3',
  'MYK Seviye 4',
  'MYK Seviye 5',
  'USTA Belgesi',
  'Kalfa Belgesi',
  'Çıraklık Belgesi',
  'İş Güvenliği Uzmanlığı Sertifikası',
  'A Sınıfı İSG',
  'B Sınıfı İSG',
  'C Sınıfı İSG',
  'İşyeri Hekimliği',
  'SRC 1',
  'SRC 2',
  'SRC 3',
  'SRC 4',
  'Psikoteknik',
];

export const EXTRA_FIELDS_TR = [
  'Yapay Zeka Mühendisliği',
  'Veri Mühendisliği',
  'Bilişim Sistemleri Mühendisliği',
  'Kontrol ve Otomasyon Mühendisliği',
  'Enerji Sistemleri Mühendisliği',
  'Nükleer Enerji Mühendisliği',
  'Tekstil Mühendisliği',
  'Deri Mühendisliği',
  'Ağaç İşleri Endüstri Mühendisliği',
  'Gemi İnşaatı ve Gemi Makineleri Mühendisliği',
  'Deniz Ulaştırma İşletme Mühendisliği',
  'Gemi ve Yat Tasarımı',
  'Havacılık ve Uzay Mühendisliği',
  'Uçak Gövde Motor Bakım',
  'Pilotaj',
  'Sivil Havacılık Kabin Hizmetleri',
  'Sivil Hava Ulaştırma İşletmeciliği',
  'Lojistik Yönetimi',
  'Uluslararası Lojistik ve Taşımacılık',
  'Gümrük İşletme',
  'Denizcilik İşletmeleri Yönetimi',
  'Sermaye Piyasaları',
  'Sigortacılık ve Risk Yönetimi',
  'Aktüerya',
  'Ekonometri',
  'Kamu Yönetimi',
  'Yerel Yönetimler',
  'Sosyal Hizmet',
  'Çocuk Gelişimi',
  'Aile ve Tüketici Bilimleri',
  'Beslenme ve Diyetetik',
  'Odyoloji',
  'Dil ve Konuşma Terapisi',
  'Ergoterapi',
  'Perfüzyon',
  'Acil Yardım ve Afet Yönetimi',
  'İlk ve Acil Yardım',
  'Tıbbi Görüntüleme Teknikleri',
  'Tıbbi Laboratuvar Teknikleri',
  'Anestezi',
  'Ameliyathane Hizmetleri',
  'Diyaliz',
  'Odyometri',
  'Optisyenlik',
  'Ortez Protez',
  'Eczane Hizmetleri',
  'Yaşlı Bakımı',
  'Engelli Bakımı ve Rehabilitasyon',
  'Tıbbi Dokümantasyon ve Sekreterlik',
  'Sağlık Yönetimi',
  'Sağlık Kurumları İşletmeciliği',
  'Adalet',
  'Ceza İnfaz ve Güvenlik Hizmetleri',
  'Sosyal Güvenlik',
  'Çalışma Ekonomisi ve Endüstri İlişkileri',
  'Kamu Maliyesi',
  'Maliye ve Vergi',
  'Gayrimenkul Geliştirme',
  'Tapu ve Kadastro',
  'Harita ve Kadastro',
  'Mimari Restorasyon',
  'İç Mekan Tasarımı',
  'Moda Tasarımı',
  'Tekstil Tasarımı',
  'Takı Tasarımı',
  'Seramik ve Cam',
  'Heykel',
  'Resim',
  'Grafik',
  'Animasyon',
  'Dijital Oyun Tasarımı',
  'Yeni Medya',
  'Halkla İlişkiler ve Reklamcılık',
  'Reklamcılık',
  'Fotoğraf',
  'Sinema ve Televizyon',
  'Sahne Sanatları',
  'Konservatuvar',
  'Türk Halk Müziği',
  'Türk Sanat Müziği',
  'Beden Eğitimi ve Spor Öğretmenliği',
  'Antrenörlük Eğitimi',
  'Spor Yöneticiliği',
  'Rekreasyon',
  'İlahiyat',
  'İslami İlimler',
  'Felsefe',
  'Felsefe Grubu Öğretmenliği',
  'Tarih Öğretmenliği',
  'Coğrafya',
  'Coğrafya Öğretmenliği',
  'Türkçe Öğretmenliği',
  'Almanca Öğretmenliği',
  'Fransızca Öğretmenliği',
  'Arapça Öğretmenliği',
  'Özel Eğitim Öğretmenliği',
  'Zihin Engelliler Öğretmenliği',
  'İlköğretim Matematik Öğretmenliği',
  'Fen Bilgisi Öğretmenliği',
  'Sosyal Bilgiler Öğretmenliği',
  'Bilgisayar ve Öğretim Teknolojileri',
  'Moleküler Biyoloji ve Genetik',
  'Biyomühendislik',
  'Biyomedikal Mühendisliği',
  'Nanoteknoloji Mühendisliği',
  'Malzeme Bilimi ve Mühendisliği',
  'Jeoloji Mühendisliği',
  'Jeofizik Mühendisliği',
  'Maden Mühendisliği',
  'Jeodezi ve Fotogrametri',
  'Şehir ve Bölge Planlama',
  'Peyzaj Mimarlığı',
  'Su Ürünleri',
  'Balıkçılık Teknolojisi',
  'Veterinerlik',
  'Bitki Koruma',
  'Bahçe Bitkileri',
  'Tarla Bitkileri',
  'Zootekni',
  'Süt Teknolojisi',
  'Gıda Teknolojisi',
  'Aşçılık',
  'Pastacılık ve Ekmekçilik',
  'Turizm ve Otel İşletmeciliği',
  'Turizm Rehberliği',
  'Yiyecek İçecek İşletmeciliği',
  'Gastronomi ve Mutfak Sanatları',
  'Rekreasyon Yönetimi',
  'Havacılık Yönetimi',
  'Lojistik',
  'Dış Ticaret',
  'E-ticaret ve Pazarlama',
  'Halkla İlişkiler',
  'Medya ve İletişim',
  'Yeni Medya ve İletişim',
  'Bilgi ve Belge Yönetimi',
  'Arşivcilik',
  'Mütercim Tercümanlık',
  'İngiliz Dili ve Edebiyatı',
  'Amerikan Kültürü ve Edebiyatı',
  'Alman Dili ve Edebiyatı',
  'Fransız Dili ve Edebiyatı',
  'Arap Dili ve Edebiyatı',
  'Rus Dili ve Edebiyatı',
  'Japon Dili ve Edebiyatı',
  'Çin Dili ve Edebiyatı',
  'Kore Dili ve Edebiyatı',
  'İspanyol Dili ve Edebiyatı',
  'Karşılaştırmalı Edebiyat',
  'Dilbilim',
  'Antropoloji',
  'Arkeoloji',
  'Sanat Tarihi',
  'Kültürel Çalışmalar',
];

export const EXTRA_DISTRICTS_TR = [
  'İstanbul / Kadıköy',
  'İstanbul / Beşiktaş',
  'İstanbul / Üsküdar',
  'İstanbul / Şişli',
  'İstanbul / Beyoğlu',
  'İstanbul / Fatih',
  'İstanbul / Bakırköy',
  'İstanbul / Ataşehir',
  'İstanbul / Maltepe',
  'İstanbul / Kartal',
  'İstanbul / Pendik',
  'İstanbul / Tuzla',
  'İstanbul / Ümraniye',
  'İstanbul / Sancaktepe',
  'İstanbul / Çekmeköy',
  'İstanbul / Beykoz',
  'İstanbul / Sarıyer',
  'İstanbul / Kağıthane',
  'İstanbul / Eyüpsultan',
  'İstanbul / Gaziosmanpaşa',
  'İstanbul / Bayrampaşa',
  'İstanbul / Esenler',
  'İstanbul / Bağcılar',
  'İstanbul / Güngören',
  'İstanbul / Bahçelievler',
  'İstanbul / Küçükçekmece',
  'İstanbul / Avcılar',
  'İstanbul / Beylikdüzü',
  'İstanbul / Esenyurt',
  'İstanbul / Büyükçekmece',
  'İstanbul / Başakşehir',
  'İstanbul / Arnavutköy',
  'İstanbul / Sultangazi',
  'İstanbul / Sultanbeyli',
  'Ankara / Çankaya',
  'Ankara / Keçiören',
  'Ankara / Yenimahalle',
  'Ankara / Mamak',
  'Ankara / Etimesgut',
  'Ankara / Sincan',
  'Ankara / Altındağ',
  'Ankara / Pursaklar',
  'Ankara / Gölbaşı',
  'Ankara / Polatlı',
  'İzmir / Konak',
  'İzmir / Bornova',
  'İzmir / Karşıyaka',
  'İzmir / Buca',
  'İzmir / Bayraklı',
  'İzmir / Çiğli',
  'İzmir / Gaziemir',
  'İzmir / Balçova',
  'İzmir / Narlıdere',
  'İzmir / Karabağlar',
  'İzmir / Torbalı',
  'İzmir / Menemen',
  'İzmir / Aliağa',
  'Bursa / Nilüfer',
  'Bursa / Osmangazi',
  'Bursa / Yıldırım',
  'Bursa / Gemlik',
  'Bursa / İnegöl',
  'Antalya / Muratpaşa',
  'Antalya / Konyaaltı',
  'Antalya / Kepez',
  'Antalya / Aksu',
  'Antalya / Döşemealtı',
  'Antalya / Alanya',
  'Antalya / Manavgat',
  'Antalya / Serik',
  'Adana / Seyhan',
  'Adana / Çukurova',
  'Adana / Yüreğir',
  'Adana / Sarıçam',
  'Gaziantep / Şahinbey',
  'Gaziantep / Şehitkamil',
  'Gaziantep / Oğuzeli',
  'Kocaeli / İzmit',
  'Kocaeli / Gebze',
  'Kocaeli / Darıca',
  'Kocaeli / Körfez',
  'Kocaeli / Gölcük',
  'Konya / Selçuklu',
  'Konya / Meram',
  'Konya / Karatay',
  'Mersin / Yenişehir',
  'Mersin / Mezitli',
  'Mersin / Toroslar',
  'Mersin / Akdeniz',
  'Mersin / Tarsus',
  'Kayseri / Melikgazi',
  'Kayseri / Kocasinan',
  'Kayseri / Talas',
  'Eskişehir / Tepebaşı',
  'Eskişehir / Odunpazarı',
  'Samsun / İlkadım',
  'Samsun / Atakum',
  'Samsun / Canik',
  'Trabzon / Ortahisar',
  'Trabzon / Akçaabat',
  'Diyarbakır / Bağlar',
  'Diyarbakır / Kayapınar',
  'Diyarbakır / Yenişehir',
  'Diyarbakır / Sur',
  'Şanlıurfa / Eyyübiye',
  'Şanlıurfa / Haliliye',
  'Şanlıurfa / Karaköprü',
  'Hatay / Antakya',
  'Hatay / İskenderun',
  'Hatay / Defne',
  'Muğla / Bodrum',
  'Muğla / Fethiye',
  'Muğla / Marmaris',
  'Muğla / Milas',
  'Muğla / Mentese',
  'Aydın / Efeler',
  'Aydın / Kuşadası',
  'Aydın / Didim',
  'Aydın / Söke',
  'Denizli / Merkezefendi',
  'Denizli / Pamukkale',
  'Tekirdağ / Süleymanpaşa',
  'Tekirdağ / Çorlu',
  'Tekirdağ / Çerkezköy',
  'Sakarya / Adapazarı',
  'Sakarya / Serdivan',
  'Sakarya / Erenler',
  'Balıkesir / Karesi',
  'Balıkesir / Altıeylül',
  'Balıkesir / Bandırma',
  'Balıkesir / Edremit',
  'Manisa / Yunusemre',
  'Manisa / Şehzadeler',
  'Manisa / Turgutlu',
  'Manisa / Akhisar',
  'Kahramanmaraş / Onikişubat',
  'Kahramanmaraş / Dulkadiroğlu',
  'Malatya / Battalgazi',
  'Malatya / Yeşilyurt',
  'Van / İpekyolu',
  'Van / Tuşba',
  'Van / Edremit',
  'Erzurum / Yakutiye',
  'Erzurum / Palandöken',
  'Erzurum / Aziziye',
];

export const EXTRA_WORLD_CITIES = [
  'Birmingham',
  'Manchester',
  'Leeds',
  'Glasgow',
  'Edinburgh',
  'Dublin',
  'Lisbon',
  'Porto',
  'Barcelona',
  'Valencia',
  'Seville',
  'Lyon',
  'Marseille',
  'Toulouse',
  'Nice',
  'Geneva',
  'Basel',
  'Lausanne',
  'Prague',
  'Budapest',
  'Warsaw',
  'Krakow',
  'Stockholm',
  'Oslo',
  'Copenhagen',
  'Helsinki',
  'Athens',
  'Thessaloniki',
  'Sofia',
  'Bucharest',
  'Belgrade',
  'Zagreb',
  'Sarajevo',
  'Skopje',
  'Tirana',
  'Nicosia',
  'Famagusta',
  'Jeddah',
  'Mecca',
  'Medina',
  'Dammam',
  'Kuwait City',
  'Manama',
  'Muscat',
  'Amman',
  'Beirut',
  'Baghdad',
  'Erbil',
  'Tehran',
  'Tbilisi',
  'Baku',
  'Yerevan',
  'Almaty',
  'Tashkent',
  'Bishkek',
  'Casablanca',
  'Rabat',
  'Tunis',
  'Algiers',
  'Alexandria',
  'Nairobi',
  'Lagos',
  'Johannesburg',
  'Cape Town',
  'Accra',
  'Addis Ababa',
  'Chicago',
  'Houston',
  'Dallas',
  'San Francisco',
  'Seattle',
  'Boston',
  'Miami',
  'Atlanta',
  'Washington',
  'Toronto',
  'Vancouver',
  'Montreal',
  'Mexico City',
  'Monterrey',
  'Guadalajara',
  'Bogotá',
  'Lima',
  'Santiago',
  'Buenos Aires',
  'São Paulo',
  'Rio de Janeiro',
  'Brasília',
  'Sydney',
  'Melbourne',
  'Auckland',
  'Seoul',
  'Busan',
  'Osaka',
  'Kyoto',
  'Shanghai',
  'Beijing',
  'Shenzhen',
  'Hong Kong',
  'Taipei',
  'Bangkok',
  'Jakarta',
  'Kuala Lumpur',
  'Manila',
  'Ho Chi Minh City',
  'Hanoi',
  'New Delhi',
  'Mumbai',
  'Bengaluru',
  'Chennai',
  'Hyderabad',
  'Karachi',
  'Lahore',
  'Islamabad',
  'Dhaka',
  'Colombo',
];

export const EXTRA_SKILLS_EN = [
  'Cold calling',
  'Proposal writing',
  'Pricing',
  'Contract management',
  'Vendor management',
  'Inventory counting',
  'Fleet management',
  'Payroll',
  'Tax filing',
  'Internal audit',
  'Cash flow',
  'Collections',
  'Welding',
  'Machining',
  'CNC programming',
  'Forklift license',
  'Heavy vehicle license',
  'Cooking',
  'Pastry',
  'Bartending',
  'Housekeeping',
  'Front desk',
  'Translation',
  'Training',
  'Coaching',
  'Italian',
  'Portuguese',
  'Dutch',
  'Persian',
  'Japanese',
  'Chinese',
  'Korean',
];

export const EXTRA_POSITIONS_EN = [
  'Sales Coordinator',
  'Key Account Manager',
  'E-commerce Manager',
  'Brand Manager',
  'Category Manager',
  'Export Manager',
  'Import Manager',
  'Production Planner',
  'Production Engineer',
  'Shift Supervisor',
  'Quality Engineer',
  'R&D Engineer',
  'Maintenance Engineer',
  'CNC Operator',
  'Welder',
  'Warehouse Clerk',
  'Inventory Specialist',
  'Payroll Specialist',
  'Bank Teller',
  'Credit Analyst',
  'Insurance Specialist',
  'Real Estate Agent',
  'Architect',
  'Interior Designer',
  'QA Engineer',
  'DevOps Engineer',
  'System Administrator',
  'Network Administrator',
  'Cybersecurity Specialist',
  'Data Scientist',
  'SEO Specialist',
  'Content Specialist',
  'Photographer',
  'Videographer',
  'Translator',
  'Teacher',
  'Doctor',
  'Dentist',
  'Veterinarian',
  'Chef',
  'Waiter',
  'Barista',
  'Receptionist',
  'Tour Guide',
  'Flight Attendant',
  'Courier',
  'Truck Driver',
  'Security Guard',
  'Cashier',
  'Intern',
];

export const EXTRA_FIELDS_EN = [
  'Artificial Intelligence Engineering',
  'Data Engineering',
  'Biomedical Engineering',
  'Aerospace Engineering',
  'Petroleum Engineering',
  'Textile Engineering',
  'Naval Architecture',
  'Urban Planning',
  'Landscape Architecture',
  'Gastronomy',
  'Hotel Management',
  'Tourism Guidance',
  'Aviation Management',
  'Public Administration',
  'Social Work',
  'Nutrition and Dietetics',
  'Physiotherapy',
  'Midwifery',
  'Pharmacy Technician',
  'Fashion Design',
  'Game Design',
  'Film and Television',
  'Translation and Interpreting',
  'Theology',
  'Philosophy',
  'Archaeology',
  'Art History',
  'Molecular Biology and Genetics',
  'Veterinary Science',
  'Agricultural Engineering',
  'Food Technology',
  'Sports Management',
  'Special Education',
  'Preschool Education',
];
